/* Alta del coach: opciones oficiales, cuenta y plantilla anual. */
function officialCategory(name){const value=String(name||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();if(/\bU[ -]?9\b|PRE[ -]?MINI/.test(value))return 'Mini U11';if(/\bU[ -]?11\b|\bMINI\b/.test(value))return 'Mini U11';if(/\bU[ -]?13\b|INFANTIL/.test(value))return 'U13';if(/\bU[ -]?15\b|CADET/.test(value))return 'U15';if(/\bU[ -]?17\b|JUVENIL/.test(value))return 'U17';if(/\bU[ -]?19\b/.test(value))return 'U19';if(/\bU[ -]?21\b/.test(value))return 'U21';if(/MAYORES|PRIMERA|SUPERIOR/.test(value))return 'Mayores';return null;}
document.addEventListener('DOMContentLoaded',()=>{
 const host=document.getElementById('nextlevel-onboarding');if(!host)return;
 const n=(tag,text,parent)=>{const e=document.createElement(tag);if(text!=null)e.textContent=text;if(parent)parent.append(e);return e;};
 const field=(label,type='text')=>{const box=n('label',label,host);box.style.cssText='display:block;margin:12px 0';const input=n('input',null,box);input.type=type;input.style.cssText='display:block;width:100%;padding:10px;background:#102035;color:#e2e8f0;border:1px solid #35516c;border-radius:8px;font:inherit';return input;};
 const query=field('Club o localidad'),season=field('Temporada','number');season.value=String(new Date().getFullYear());
 const categoryBox=n('label','Categoría',host);categoryBox.style.cssText='display:block;margin:12px 0';
 const categoryFilter=n('select',null,categoryBox);categoryFilter.style.cssText='display:block;width:100%;padding:10px;background:#102035;color:#e2e8f0;border:1px solid #35516c;border-radius:8px;font:inherit';categoryFilter.disabled=true;
 n('option','Primero elegí un club',categoryFilter).value='';
 const search=n('button','Buscar en CABB',host);search.className='btn-sm';const results=n('div',null,host),details=n('div',null,host),status=n('p','Buscá el club y luego elegí la categoría y el torneo.',host);status.setAttribute('role','status');
 let selectedTeam=null,selectedPlayer=null,busy=false,teams=[],selectedClub=null;
 async function invoke(payload){const {data,error}=await supa.functions.invoke('nextlevel-onboard',{body:payload});if(error){let message='No se pudo conectar al alta. Verificá que la función nextlevel-onboard esté desplegada en Supabase.';try{const body=await error.context?.json();if(body?.error)message=body.error;}catch(e){}throw Error(message);}if(data.error)throw Error(data.error);return data;}
 function button(text,parent,handler){const b=n('button',text,parent);b.type='button';b.className='btn-sm';b.style.cssText='display:block;margin:10px 0;text-align:left';b.onclick=handler;return b;}
 function resetCategory(){categoryFilter.replaceChildren();n('option','Primero elegí un club',categoryFilter).value='';categoryFilter.disabled=true;}
 function showClubs(){results.replaceChildren();details.replaceChildren();selectedClub=selectedTeam=selectedPlayer=null;resetCategory();for(const club of [...new Set(teams.map(t=>t.club))])button(club,results,()=>chooseClub(club));status.textContent=teams.length?'Elegí el club.':'No hay coincidencias para esta temporada.';}
 function chooseClub(club){if(busy)return;selectedClub=club;selectedTeam=selectedPlayer=null;details.replaceChildren();categoryFilter.replaceChildren();n('option','Elegí una categoría',categoryFilter).value='';for(const name of [...new Set(teams.filter(t=>t.club===club).map(t=>t.categoryName))].sort()){n('option',name,categoryFilter).value=name;}categoryFilter.disabled=false;renderTeams();status.textContent='Elegí la categoría del club.';}
 function renderTeams(){results.replaceChildren();n('h3',selectedClub,results);button('Cambiar club',results,()=>{if(!busy)showClubs();});const matches=teams.filter(t=>t.club===selectedClub && t.categoryName===categoryFilter.value);if(selectedTeam){n('p',selectedTeam.categoryName+' · '+selectedTeam.competition+' · '+selectedTeam.federation,results);button('Cambiar torneo',results,()=>{if(busy)return;selectedTeam=selectedPlayer=null;details.replaceChildren();renderTeams();status.textContent='Elegí el torneo.';});return;}for(const team of matches)button(team.competition+' · '+team.federation,results,()=>chooseTeam(team));}
 categoryFilter.onchange=()=>{selectedTeam=selectedPlayer=null;details.replaceChildren();renderTeams();status.textContent=categoryFilter.value?'Elegí el torneo.':'Elegí una categoría.';};
 search.onclick=async()=>{if(busy)return;busy=true;search.disabled=true;categoryFilter.disabled=true;results.replaceChildren();details.replaceChildren();selectedClub=selectedTeam=selectedPlayer=null;teams=[];status.textContent='Buscando clubes oficiales…';try{if(!/^20\d{2}$/.test(season.value))throw Error('Revisá la temporada');const data=await invoke({action:'teams',query:query.value,season:season.value});teams=data.teams || [];showClubs();}catch(e){resetCategory();status.textContent=e.message;}finally{busy=false;search.disabled=false;}};
 async function chooseTeam(team){if(busy)return;busy=true;categoryFilter.disabled=true;details.replaceChildren();selectedTeam=team;renderTeams();status.textContent='Consultando plantel…';try{const data=await invoke({action:'roster',team});for(const player of data.players)button(player.name+' · '+(player.pj ?? '—')+' PJ',details,()=>choosePlayer(player));status.textContent=data.players.length?'Confirmá el jugador del plantel.':'Este plantel no tiene jugadores disponibles.';}catch(e){selectedTeam=null;renderTeams();status.textContent=e.message;}finally{busy=false;categoryFilter.disabled=false;}}
 function choosePlayer(player){selectedPlayer=player;details.replaceChildren();n('h3',player.name,details);const form=n('form',null,details);
 const entry=(label,type='text',required=true)=>{const box=n('label',label,form);box.style.cssText='display:block;margin:12px 0';const i=n('input',null,box);i.type=type;i.required=required;i.style.cssText='display:block;width:100%;padding:10px;background:#102035;color:#e2e8f0;border:1px solid #35516c;border-radius:8px;font:inherit';return i;};
 const name=entry('Nombre para mostrar');name.value=player.name;const email=entry('Correo del acceso jugador/padre','email');const password=entry('Contraseña inicial (solo si la cuenta es nueva)','password');password.required=false;password.autocomplete='new-password';password.minLength=8;
 const shirt=entry('Dorsal (opcional)','number',false);shirt.removeAttribute('required');shirt.placeholder='Dejalo vacío si no lo sabés';shirt.min='0';shirt.max='99';if(player.dorsal!=null)shirt.value=String(player.dorsal);
 const categoryLabel=n('label','Categoría de esta temporada',form),category=n('select',null,categoryLabel);for(const value of ['Mini U11','U13','U15','U17','U19','U21','Mayores']){const o=n('option',value,category);o.value=value;}const detectedCategory=officialCategory(selectedTeam.categoryName);if(detectedCategory){category.value=detectedCategory;category.disabled=true;}else{category.value='';category.required=true;}n('small',detectedCategory?'Asignada automáticamente según la categoría oficial CABB.':'Categoría oficial no reconocida: confirmala antes de crear el perfil.',categoryLabel);
 const label=entry('Nombre del torneo en el perfil');label.value=/MINI/i.test(selectedTeam.categoryName)?'FEBAMBA Mini':/FEMENINA METROPOLITANA/i.test(selectedTeam.federation)?'AFMB':/FEDERAL/i.test(selectedTeam.categoryName)?'Federal CABB':'FEBAMBA';
 n('p','La cuenta existente se vincula sin cambiar su contraseña. Para una cuenta nueva, elegí una contraseña inicial. No se envían correos automáticamente.',form);
 const submit=n('button','Crear / vincular y cargar partidos',form);submit.type='submit';submit.className='btn-sm';
 form.onsubmit=async event=>{event.preventDefault();if(busy || !form.reportValidity())return;busy=true;submit.disabled=true;status.textContent='Creando el perfil y su configuración…';try{const created=await invoke({action:'create',team:selectedTeam,cabbName:selectedPlayer.name,name:name.value,email:email.value,password:password.value,category:category.value,tournamentLabel:label.value,dorsal:shirt.value===''?null:Number(shirt.value)});password.value='';status.textContent='Perfil creado. Importando actas oficiales…';
 const link=n('a','Abrir perfil',details);link.href=created.url;link.className='btn-sm';
 try{const sync=await invoke({action:'sync',playerId:created.playerId,season:selectedTeam.season});status.textContent='Listo: '+sync.games+' partidos guardados y perfil '+created.template+'.';}catch(e){status.textContent='El perfil está creado. La importación quedó pendiente: '+e.message;const retry=n('button','Reintentar importación',details);retry.className='btn-sm';retry.onclick=async()=>{retry.disabled=true;try{const r=await invoke({action:'sync',playerId:created.playerId,season:selectedTeam.season});status.textContent='Listo: '+r.games+' partidos sincronizados.';}catch(err){status.textContent=err.message;}finally{retry.disabled=false;}};}
 if(typeof loadAll==='function'){await loadAll();renderPlayers();renderSummary();renderMsgPlayerTabs();}
 }catch(e){status.textContent=e.message;}finally{busy=false;submit.disabled=false;}};
 }
});
