(function(){
'use strict';
const points=[6,8,9,11,7,12,8,10,13,9,11,8,12,14,10,9,13,14];
const games=points.map((pts,i)=>({date:`2026-${String(3+Math.floor(i/3)).padStart(2,'0')}-${String(3+(i%3)*7).padStart(2,'0')}`,rival:['Los Robles','Estrella Sur','Atlético Norte'][i%3],pts,reb:3+i%5,ast:1+i%4,min:14+i%7,val:pts+3+(i%5),score:`${45+i%15}–${40+i%11}`}));
const avg=k=>(games.reduce((n,g)=>n+g[k],0)/games.length).toFixed(1);
const card=(title,body)=>`<div class="card"><div class="card-ttl">${title}</div>${body}</div>`;
const metric=(value,label)=>`<div class="stat-cell"><div class="stat-val">${value}</div><div>${label}</div></div>`;
const note='<p class="demo-note">DEMO · Todos los datos de esta página son ficticios.</p>';
const fill=(id,html)=>document.getElementById('tab-'+id).innerHTML=html;
function chart(key){const values=games.map(g=>g[key]),max=Math.max(...values)+3;return `<svg class="demo-chart" viewBox="0 0 680 235" role="img" aria-label="Evolución ficticia por partido"><line x1="30" y1="195" x2="650" y2="195" stroke="#64748b"/><polyline fill="none" stroke="#f97316" stroke-width="4" points="${values.map((v,i)=>`${35+i*35},${190-v/max*155}`).join(' ')}"/>${values.map((v,i)=>`<circle cx="${35+i*35}" cy="${190-v/max*155}" r="5" fill="#f97316"><title>Partido ${i+1}: ${v}</title></circle>`).join('')}${[0,5,11,17].map(i=>`<text x="${35+i*35}" y="220" text-anchor="middle" fill="#64748b" font-size="14">P${i+1}</text>`).join('')}</svg>`;}
fill('dash',card('🏠 Hola, Sofía',`<p>Estás sumando experiencia y encontrando tu lugar en el equipo. Celebrá tus avances y seguí practicando.</p>${note}`)+card('📊 Mi temporada',`<div class="demo-metrics">${metric(avg('pts'),'Puntos por partido')}${metric(avg('reb'),'Rebotes por partido')}${metric(avg('min'),'Minutos por partido')}${metric(18,'Partidos')}</div>`)+card('📈 Mis últimos partidos',chart('pts'))+card('🏆 Un avance para celebrar','<p>En tus últimos cinco partidos promediaste 12 puntos. ¡Seguí animándote a participar!</p>')+card('🎯 Mi próximo paso','<p>Practicar una rutina de tiros libres y volver a la próxima jugada después de un error.</p>'));
fill('perfil',card('👤 Sobre mí',`<label class="demo-field">Posición<select><option>Escolta</option><option>Base</option><option>Alero</option><option>Ala-pívot</option><option>Pívot</option></select></label><label class="demo-field">Mi sueño<textarea>Disfrutar del básquet y crecer con mi equipo.</textarea></label><label class="demo-field">Mi objetivo de temporada<textarea>Ganar confianza para atacar el aro y ayudar a mis compañeras.</textarea></label><p>Áreas a trabajar</p><label><input type="checkbox" checked> Tiros libres</label><br><label><input type="checkbox" checked> Confianza después de un error</label><br><label><input type="checkbox"> Pase y lectura del juego</label>${note}<p class="demo-note">Podés editar los ejemplos; se reinician al recargar.</p>`));
const recent=games.slice(-5).reverse();
fill('rend',card('📊 Estadísticas de temporada',`<div class="demo-metrics">${metric(avg('pts'),'Puntos por partido')}${metric(avg('reb'),'Rebotes por partido')}${metric(avg('ast'),'Asistencias por partido')}${metric(avg('val'),'Valoración por partido')}</div>${note}`)+card('🏆 Hitos de temporada',`<div class="demo-metrics">${metric('🏀 14','Mayor cantidad de puntos')}${metric('🙌 7','Mayor cantidad de rebotes')}${metric('⏱️ 20','Mayor tiempo de juego')}</div>`)+card('🗓️ Últimos partidos',recent.map(g=>`<div class="stat-cell" style="margin:10px 0;text-align:left"><strong>${g.date} · vs ${g.rival} · ${g.score}</strong><p>${g.pts} PTS · ${g.reb} REB · ${g.ast} AST · ${g.min} MIN</p></div>`).join(''))+card('🔥 Mapa de tiro de la temporada',`<p>Ejemplo por zonas · 180 intentos · 72 convertidos (40.0%).</p><svg class="demo-chart" viewBox="0 0 500 420" role="img" aria-label="Media cancha ficticia: zona pintada 48%, media distancia 32%, triples 20%"><rect x="15" y="15" width="470" height="385" fill="#0b1528" stroke="#94a3b8"/><path d="M 60 15 V 75 A 190 190 0 0 0 440 75 V 15" fill="#29B6F6" fill-opacity=".4" stroke="#94a3b8"/><rect x="165" y="15" width="170" height="155" fill="#00E676" fill-opacity=".6" stroke="#e2e8f0"/><circle cx="250" cy="52" r="12" fill="none" stroke="#f97316" stroke-width="4"/><path d="M 165 170 A 85 85 0 0 0 335 170" fill="#FFD740" fill-opacity=".6" stroke="#e2e8f0"/><text x="250" y="110" text-anchor="middle" fill="white" font-size="21">Pintada · 48%</text><text x="250" y="218" text-anchor="middle" fill="white" font-size="18">Media distancia · 32%</text><text x="250" y="345" text-anchor="middle" fill="white" font-size="18">Triple · 20%</text></svg><p>Tu mayor volumen está cerca del aro. Una propuesta es practicar finalizaciones con ambas manos y revisar los tiros con el coach.</p>${note}`));
fill('coach',card('🧠 Mi perfil según los datos',`<p>Participás con puntos, rebotes y pases. Los números ayudan a conversar sobre tu juego; tu técnica y tus decisiones también necesitan observación del coach.</p>${note}`)+card('🌱 Mis prioridades','<p><strong>1. Finalizar cerca del aro:</strong> practicar con ambas manos.</p><p><strong>2. Tiros libres:</strong> repetir una rutina corta y tranquila.</p><p><strong>3. Volver después de un error:</strong> elegir una acción para la siguiente posesión.</p>')+card('💬 Mensaje del coach','<p>“Sofía, me gustó cómo volviste a defender después de perder la pelota. Esta semana vamos a practicar el primer paso y una rutina de tiro libre.”</p><p class="demo-note">Mensaje ficticio · No se envían mensajes desde la demo.</p>'));
fill('prog',card('📈 Mi evolución',`<label class="demo-field">Qué quiero ver<select id="demo-evolution"><option value="pts">Puntos</option><option value="reb">Rebotes</option><option value="min">Minutos</option><option value="val">Valoración</option></select></label><div id="demo-chart">${chart('pts')}</div>${note}`)+card('🎯 Evolución de efectividad',`<div class="demo-metrics">${metric('38% → 44%','Cancha · ejemplo de mejora')}${metric('52% → 60%','Libres · ejemplo de mejora')}</div><p>Las muestras son pequeñas: conversalo con tu coach antes de sacar conclusiones.</p>`));
fill('plan',card('🎯 Mi plan de dos semanas','<p>Pequeños pasos, con revisión semanal junto al coach.</p><label class="demo-field"><input type="checkbox"> Practiqué 20 tiros libres con mi rutina</label><label class="demo-field"><input type="checkbox"> Probé finalizar con ambas manos</label><label class="demo-field"><input type="checkbox"> Volví a la siguiente jugada después de un error</label><p id="demo-progress">0 de 3 prácticas registradas en esta demostración.</p>')+card('🧘 Tips y trabajo mental','<h3>🫁 Antes de lanzar</h3><p>Respirá, mirá el aro y repetí tu rutina. Un tiro a la vez.</p><h3>🔄 Después de un error</h3><p>Decite “siguiente jugada” y elegí una acción: volver, marcar o pedir la pelota.</p><label class="demo-field">¿Cómo me fue hoy?<textarea placeholder="Hoy me animé a…"></textarea></label>'));
fill('fis',card('💪 Mis evaluaciones físicas',`<p>Ejemplos para mostrar el seguimiento. No son mediciones de una persona real.</p><div class="demo-metrics">${metric('8.2','Resistencia · nivel')}${metric('31 cm','Salto vertical')}${metric('4.2 s','Velocidad · 20 metros')}${metric('11.8 s','Agilidad')}${metric('12 cm','Flexibilidad')}</div>${note}`)+card('📅 Próxima evaluación','<p>Revisar junto al preparador dentro de cuatro semanas, respetando el crecimiento y la recuperación.</p>'));
document.querySelectorAll('.tab-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab-btn').forEach(x=>x.classList.toggle('on',x===b));document.querySelectorAll('.tab-pane').forEach(x=>x.classList.toggle('on',x.id==='tab-'+b.dataset.tab));}));
document.getElementById('demo-evolution').addEventListener('change',e=>document.getElementById('demo-chart').innerHTML=chart(e.target.value));
document.querySelectorAll('#tab-plan input').forEach(input=>input.addEventListener('change',()=>document.getElementById('demo-progress').textContent=document.querySelectorAll('#tab-plan input:checked').length+' de 3 prácticas registradas en esta demostración.'));
window.doLogout=()=>{window.location.href='login.html';};
})();
