/* Dorsal visible editable. Las estadísticas y tiros conservan el dorsal del acta. */
(function(){
 function parseDorsal(value){if(String(value).trim()==='')return null;const n=Number(value);if(!Number.isInteger(n) || n<0 || n>99)throw Error('Elegí un dorsal entero entre 0 y 99.');return n;}
 async function mount(){const host=document.getElementById('tab-perfil') || document.getElementById('mini-perfil');if(!host)return;
 const id=window.NextLevelPlayer?.playerId || (typeof PLAYER_ID!=='undefined'?PLAYER_ID:null);if(!id)return;
 const client=typeof _supa!=='undefined'?_supa:supabase.createClient(NextLevelAppConfig.url,NextLevelAppConfig.anonKey);
 const section=document.createElement('section');section.className='card';section.style.cssText='padding:16px;margin-bottom:14px';const label=document.createElement('label');label.textContent='Mi dorsal';label.style.cssText='display:block;color:#38bdf8;font-weight:800';const input=document.createElement('input');input.type='number';input.min='0';input.max='99';input.step='1';input.placeholder='Sin informar';input.style.cssText='display:block;padding:10px;margin-top:8px;font:inherit;width:140px;background:#0f1e35;color:#e2e8f0;border:1px solid #475569;border-radius:8px';label.append(input);section.append(label);const status=document.createElement('p');status.style.cssText='font-size:14px;color:#94a3b8';status.textContent='CABB lo completa cuando está disponible. Podés cambiarlo y se guarda automáticamente.';section.append(status);host.prepend(section);
 const apply=value=>{input.value=value ?? '';if(window.NextLevelPlayer)window.NextLevelPlayer.dorsal=value;document.querySelectorAll('.hero-num > span,#mini-avatar-placeholder').forEach(el=>el.textContent=value ?? '');const field=document.querySelector('#tab-perfil .profile-field .pf-val');if(field)field.textContent=value==null?'Sin informar':'#'+value;};
 let edited=false,revision=0,timer,queue=Promise.resolve();input.oninput=()=>{edited=true;const version=++revision;clearTimeout(timer);let dorsal;try{dorsal=parseDorsal(input.value);}catch(e){status.textContent=e.message;return;}apply(dorsal);status.textContent='Guardando dorsal…';timer=setTimeout(()=>{queue=queue.catch(()=>{}).then(async()=>{const {error}=await client.from('player_data').upsert({player_id:id,module:'profile_dorsal_v1',data:{dorsal},updated_at:new Date().toISOString()},{onConflict:'player_id,module'});if(error)throw error;if(version===revision)status.textContent=dorsal==null?'Guardado. CABB podrá completarlo en la próxima actualización.':'Dorsal guardado en Supabase.';}).catch(e=>{if(version===revision)status.textContent='No se pudo guardar: '+e.message;});},600);};
 try{const {data,error}=await client.from('player_data').select('data').eq('player_id',id).eq('module','profile_dorsal_v1').maybeSingle();if(error)throw error;if(!edited){if(data?.data?.dorsal!=null)apply(data.data.dorsal);else{const {data:p,error:pe}=await client.from('players').select('dorsal').eq('id',id).maybeSingle();if(pe)throw pe;if(!edited)apply(p?.dorsal ?? window.NextLevelPlayer?.dorsal ?? null);}}}catch(e){if(!edited)status.textContent='No se pudo cargar el dorsal: '+e.message;}
 }
 if(typeof module!=='undefined')module.exports={parseDorsal};if(typeof document!=='undefined')document.addEventListener('DOMContentLoaded',mount);
})();
