/* Alta del coach: opciones oficiales, cuenta y plantilla anual. */
document.addEventListener('DOMContentLoaded',()=>{
 const host=document.getElementById('nextlevel-onboarding');if(!host)return;
 const n=(tag,text,parent)=>{const e=document.createElement(tag);if(text!=null)e.textContent=text;if(parent)parent.append(e);return e;};
 const field=(label,type='text')=>{const box=n('label',label,host);box.style.cssText='display:block;margin:12px 0';const input=n('input',null,box);input.type=type;input.style.cssText='display:block;width:100%;padding:10px;background:#102035;color:#e2e8f0;border:1px solid #35516c;border-radius:8px;font:inherit';return input;};
 const query=field('Club o localidad'),season=field('Temporada','number');season.value=String(new Date().getFullYear());
 const search=n('button','Buscar en CABB',host);search.className='btn-sm';const results=n('div',null,host),details=n('div',null,host),status=n('p','Mini usa la plantilla de Milo; U13 en adelante usa la de Mía.',host);status.setAttribute('role','status');
 let selectedTeam=null,selectedPlayer=null,busy=false;
 async function invoke(payload){const {data,error}=await supa.functions.invoke('nextlevel-onboard',{body:payload});if(error){let message='No se pudo conectar al alta. Verificá que la función nextlevel-onboard esté desplegada en Supabase.';try{const body=await error.context?.json();if(body?.error)message=body.error;}catch(e){}throw Error(message);}if(data.error)throw Error(data.error);return data;}
 search.onclick=async()=>{if(busy)return;busy=true;search.disabled=true;results.replaceChildren();details.replaceChildren();selectedTeam=selectedPlayer=null;status.textContent='Buscando equipos oficiales…';try{if(!/^20\d{2}$/.test(season.value))throw Error('Revisá la temporada');const data=await invoke({action:'teams',query:query.value,season:season.value});if(!data.teams?.length)status.textContent='No hay coincidencias para esta temporada.';else status.textContent='Elegí el club, la categoría y el torneo correctos.';
 for(const team of data.teams){const b=n('button',team.club+' · '+team.categoryName+' · '+team.competition+' · '+team.federation,results);b.className='btn-sm';b.style.cssText='display:block;margin:10px 0;text-align:left';b.onclick=()=>chooseTeam(team);}
 }catch(e){status.textContent=e.message;}finally{busy=false;search.disabled=false;}};
 async function chooseTeam(team){if(busy)return;busy=true;details.replaceChildren();status.textContent='Consultando plantel…';try{const data=await invoke({action:'roster',team});selectedTeam=team;for(const player of data.players){const b=n('button',player.name+' · '+(player.pj ?? '—')+' PJ',details);b.className='btn-sm';b.style.cssText='display:block;margin:10px 0';b.onclick=()=>choosePlayer(player);}status.textContent='Confirmá el jugador del plantel.';}catch(e){status.textContent=e.message;}finally{busy=false;}}
 function choosePlayer(player){selectedPlayer=player;details.replaceChildren();n('h3',player.name,details);const form=n('form',null,details);
 const entry=(label,type='text')=>{const box=n('label',label,form);box.style.cssText='display:block;margin:12px 0';const i=n('input',null,box);i.type=type;i.required=true;i.style.cssText='display:block;width:100%;padding:10px;background:#102035;color:#e2e8f0;border:1px solid #35516c;border-radius:8px;font:inherit';return i;};
 const name=entry('Nombre para mostrar');name.value=player.name;const email=entry('Correo del acceso jugador/padre','email');const password=entry('Contraseña inicial (solo si la cuenta es nueva)','password');password.required=false;password.autocomplete='new-password';password.minLength=8;
 const shirt=entry('Dorsal','number');shirt.required=false;shirt.min='0';shirt.max='99';if(player.dorsal!=null)shirt.value=String(player.dorsal);
 const categoryLabel=n('label','Categoría de esta temporada',form),category=n('select',null,categoryLabel);for(const value of ['Mini U11','U13','U15','U17','U19','U21','Mayores']){const o=n('option',value,category);o.value=value;}category.value=/MINI/i.test(selectedTeam.categoryName)?'Mini U11':'U13';
 const label=entry('Nombre del torneo en el perfil');label.value=/MINI/i.test(selectedTeam.categoryName)?'FEBAMBA Mini':/FEMENINA METROPOLITANA/i.test(selectedTeam.federation)?'AFMB':/FEDERAL/i.test(selectedTeam.categoryName)?'Federal CABB':'FEBAMBA';
 n('p','La cuenta existente se vincula sin cambiar su contraseña. Para una cuenta nueva, elegí una contraseña inicial. No se envían correos automáticamente.',form);
 const submit=n('button','Crear / vincular y cargar partidos',form);submit.type='submit';submit.className='btn-sm';
 form.onsubmit=async event=>{event.preventDefault();if(busy || !form.reportValidity())return;busy=true;submit.disabled=true;status.textContent='Creando el perfil y su configuración…';try{const created=await invoke({action:'create',team:selectedTeam,cabbName:selectedPlayer.name,name:name.value,email:email.value,password:password.value,category:category.value,tournamentLabel:label.value,dorsal:shirt.value===''?null:Number(shirt.value)});password.value='';status.textContent='Perfil creado. Importando actas oficiales…';
 const link=n('a','Abrir perfil',details);link.href=created.url;link.className='btn-sm';
 try{const sync=await invoke({action:'sync',playerId:created.playerId,season:selectedTeam.season});status.textContent='Listo: '+sync.games+' partidos guardados y perfil '+created.template+'.';}catch(e){status.textContent='El perfil está creado. La importación quedó pendiente: '+e.message;const retry=n('button','Reintentar importación',details);retry.className='btn-sm';retry.onclick=async()=>{retry.disabled=true;try{const r=await invoke({action:'sync',playerId:created.playerId,season:selectedTeam.season});status.textContent='Listo: '+r.games+' partidos sincronizados.';}catch(err){status.textContent=err.message;}finally{retry.disabled=false;}};}
 if(typeof loadAll==='function'){await loadAll();renderPlayers();renderSummary();renderMsgPlayerTabs();}
 }catch(e){status.textContent=e.message;}finally{busy=false;submit.disabled=false;}};
 }
});
