/* Primera prueba Mini: identidad propia, formación y registros explícitos. */
(function(){
'use strict';
function playerMatches(name){const text=String(name).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();return /\bMILO\b/.test(text) && /\bSANCHEZ\b/.test(text);}
function mergeEntries(local,cloud){return [...new Map([...cloud,...local].map(e=>[e.id,e])).values()].sort((a,b)=>String(b.date).localeCompare(String(a.date)));}
function validPractice(entry,today){return /^\d{4}-\d{2}-\d{2}$/.test(entry.date) && entry.date<=today && Number.isFinite(Date.parse(entry.date+'T12:00:00Z')) && new Date(entry.date+'T12:00:00Z').toISOString().slice(0,10)===entry.date && !!entry.success.trim() && entry.success.length<=500 && entry.next.length<=500;}
function averageMini(rows,key){
 if(!rows.length || rows.some(r=>r[key]==null || r[key]==='' || typeof r[key]==='boolean' || !Number.isFinite(Number(r[key])) || (key!=='valoracion' && Number(r[key])<0)))return null;
 return rows.reduce((sum,r)=>sum+Number(r[key]),0)/rows.length;
}
async function load(){
const $=id=>document.getElementById(id),key='nextlevel_u11_milo_v1';let state={entries:[],physical:[],profile:{},challenge:'Mirar antes de pasar'},playerId=null,linkedUserId=null,busy=false;
try{const saved=JSON.parse(localStorage.getItem(key) || '{}');state={...state,...saved};if(!Array.isArray(state.entries))state.entries=[];if(!Array.isArray(state.physical))state.physical=[];}catch(e){}
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Buenos_Aires',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const status=text=>$('mini-status').textContent=text;
const saveLocal=()=>{try{localStorage.setItem(key,JSON.stringify(state));return true;}catch(e){status('No se pudo guardar en este dispositivo. No cierres esta página antes de conservar tu registro.');return false;}};
const show=name=>{document.querySelectorAll('.pane').forEach(p=>p.classList.toggle('on',p.id==='mini-'+name));document.querySelectorAll('.tabs button,.bottom-tabs button').forEach(b=>b.classList.toggle('on',b.dataset.pane===name));};
document.querySelectorAll('[data-pane]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.pane)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.go)));
const node=(tag,text,parent)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(parent)parent.append(n);return n;};
const render=()=>{
$('mini-challenge').value=state.challenge;$('challenge-preview').textContent=state.challenge;
$('mini-enjoy').value=state.profile.enjoy || '';$('mini-learn').value=state.profile.learn || '';$('mini-position').value=state.profile.position || 'Estoy probando distintas posiciones';
const cutoff=new Date(today+'T12:00:00Z');cutoff.setUTCDate(cutoff.getUTCDate()-6);const week=state.entries.filter(e=>e.date>=cutoff.toISOString().slice(0,10) && e.date<=today);$('week-summary').textContent=week.length ? `${week.length} experiencias registradas en los últimos siete días. Podés revisarlas con tu coach.` : 'Todavía no registraste una práctica esta semana.';
const history=$('mini-history');history.replaceChildren();node('h3','🌱 Mis experiencias recientes',history);state.entries.slice(0,10).forEach(e=>{const card=node('section',null,history);card.className='entry';node('strong',e.date+' · '+e.areas.join(' / '),card);node('p','⭐ '+e.success,card);if(e.next)node('p','🌱 '+e.next,card);node('small',e.synced ? 'Guardado en Supabase' : 'Guardado en este dispositivo · pendiente de vincular/sincronizar',card);});
};
$('mini-physical-date').value=today;$('mini-physical-date').max=today;
$('mini-date').value=today;$('mini-date').max=today;
$('mini-save-profile').addEventListener('click',()=>{state.profileDirty=true;state.profile={enjoy:$('mini-enjoy').value.trim(),learn:$('mini-learn').value.trim(),position:$('mini-position').value};if(saveLocal())status('Preferencias guardadas en este dispositivo.');});
$('mini-save-challenge').addEventListener('click',()=>{state.profileDirty=true;state.challenge=$('mini-challenge').value;if(saveLocal())status('Desafío guardado. Conversalo con tu coach.');render();});
$('mini-progress-form').addEventListener('submit',event=>{event.preventDefault();const entry={id:crypto.randomUUID(),date:$('mini-date').value,areas:[state.challenge],success:$('mini-success').value.trim(),next:$('mini-next').value.trim(),createdAt:new Date().toISOString(),source:'player_training',synced:false};if(!validPractice(entry,today)){status('Revisá la fecha y contá algo que te haya salido bien.');return;}state.entries=mergeEntries([entry],state.entries);if(saveLocal()){status('Práctica guardada en este dispositivo.');$('mini-success').value=$('mini-next').value='';}render();});
const renderPhysical=()=>{const list=$('mini-physical-history');list.replaceChildren();state.physical.slice(0,10).forEach(e=>{const card=node('section',null,list);card.className='entry';node('strong',e.date,card);node('p',Object.entries({height:'Altura',weight:'Peso',wingspan:'Envergadura'}).filter(([k])=>e[k]!=null).map(([k,label])=>`${label}: ${e[k]} ${k==='weight'?'kg':'cm'}`).join(' · '),card);node('small',e.synced?'Guardado en Supabase':'Guardado en este dispositivo',card);});};
$('mini-physical-form').addEventListener('submit',event=>{event.preventDefault();const entry={id:crypto.randomUUID(),date:$('mini-physical-date').value,source:'family_measurement',synced:false};for(const [key,id] of [['height','mini-height'],['weight','mini-weight'],['wingspan','mini-wingspan']]){const value=$(id).value;if(value!=='')entry[key]=Number(value);}
if(!validPractice({date:entry.date,success:'medida',next:''},today) || !['height','weight','wingspan'].some(k=>entry[k]!=null) || ['height','weight','wingspan'].some(k=>entry[k]!=null && (!Number.isFinite(entry[k]) || entry[k]<=0))){status('Revisá la fecha e ingresá al menos una medida positiva.');return;}
state.physical=mergeEntries([entry],state.physical);if(saveLocal())status('Medidas guardadas en este dispositivo.');renderPhysical();});renderPhysical();
let client=null;try{client=supabase.createClient(NextLevelAppConfig.url,NextLevelAppConfig.anonKey);}catch(e){}
$('mini-connect').addEventListener('click',async()=>{
if(!client){status('No se pudo conectar con Supabase. Tus registros locales se conservan.');return;}
try{const {data:auth,error:authError}=await client.auth.getUser();if(authError || !auth?.user){status('Entrá con la cuenta propia de Milo para vincular el progreso. Esta prueba sigue disponible en modo local.');return;}
const {data,error}=await client.from('players').select('id,name').eq('user_id',auth.user.id);if(error)throw error;const matches=(data || []).filter(p=>playerMatches(p.name));if(matches.length!==1){status('No se encontró un único perfil de Milo vinculado a esta cuenta. No se usa el perfil de otro jugador.');return;}playerId=matches[0].id;linkedUserId=auth.user.id;
const {data:preferences,error:prefError}=await client.from('player_data').select('data').eq('player_id',playerId).eq('module','mini_profile_v1').maybeSingle();if(prefError)throw prefError;if(preferences?.data && !state.profileDirty){const {challenge,...profile}=preferences.data;state.profile=profile;if(challenge)state.challenge=challenge;}
let rows=[];for(let from=0;;from+=500){const {data:chunk,error:readError}=await client.from('player_data').select('module,data').eq('player_id',playerId).like('module','plan_progress_v1:%').order('module').range(from,from+499);if(readError)throw readError;rows.push(...(chunk || []));if(!chunk || chunk.length<500)break;}
const cloud=rows.filter(r=>r.module.startsWith('plan_progress_v1:') && r.data?.id && Array.isArray(r.data.areas)).map(r=>({...r.data,synced:true}));const ids=new Set(cloud.map(e=>e.id));state.entries=mergeEntries(state.entries.map(e=>ids.has(e.id)?{...e,synced:true}:e),cloud);const {data:measureRows,error:measureError}=await client.from('player_data').select('module,data').eq('player_id',playerId).like('module','mini_measures_v1:%');if(measureError)throw measureError;const measures=(measureRows || []).filter(r=>r.module.startsWith('mini_measures_v1:') && r.data?.id).map(r=>({...r.data,synced:true}));const measureIds=new Set(measures.map(e=>e.id));state.physical=mergeEntries(state.physical.map(e=>measureIds.has(e.id)?{...e,synced:true}:e),measures);saveLocal();render();renderPhysical();$('mini-sync').hidden=false;status('Cuenta de Milo vinculada. Podés sincronizar sus registros cuando quieras.');
const {data:official,error:officialError}=await client.from('player_data').select('data').eq('player_id',playerId).eq('module','cabb_mini_official_v1').maybeSingle();if(officialError)throw officialError;if(official?.data)await renderOfficial(official.data);
NextLevelCoachWorkspace.mount({host:$('mini-conversation'),client,playerId,mode:'player',playerLabel:'Jugador'});
}catch(e){playerId=null;status('No se pudo vincular el perfil: '+e.message);}
});
$('mini-sync').addEventListener('click',async()=>{if(!playerId || !client || busy)return;busy=true;$('mini-sync').disabled=true;try{const {data:auth,error:authError}=await client.auth.getUser();if(authError || !auth?.user || auth.user.id!==linkedUserId)throw Error('Volvé a comprobar la cuenta de Milo antes de sincronizar.');
for(const entry of state.entries.filter(e=>!e.synced)){const {synced,...payload}=entry;const {error}=await client.from('player_data').upsert({player_id:playerId,module:'plan_progress_v1:'+entry.id,data:payload,updated_at:new Date().toISOString()},{onConflict:'player_id,module'});if(error)throw error;entry.synced=true;saveLocal();}
for(const entry of state.physical.filter(e=>!e.synced)){const {synced,...payload}=entry;const {error}=await client.from('player_data').upsert({player_id:playerId,module:'mini_measures_v1:'+entry.id,data:payload,updated_at:new Date().toISOString()},{onConflict:'player_id,module'});if(error)throw error;entry.synced=true;saveLocal();}
const {error}=await client.from('player_data').upsert({player_id:playerId,module:'mini_profile_v1',data:{...state.profile,challenge:state.challenge},updated_at:new Date().toISOString()},{onConflict:'player_id,module'});if(error)throw error;state.profileDirty=false;saveLocal();status('Prácticas, preferencias y medidas guardadas en Supabase.');render();renderPhysical();}catch(e){status('Quedaron registros pendientes: '+e.message);}finally{busy=false;$('mini-sync').disabled=false;}});
render();
async function renderOfficial(source){
try{if(!source){const response=await fetch('cabb_milo_u11_2026.json',{cache:'no-store'});if(!response.ok)throw Error();source=await response.json();}
$('mini-stat-summary').replaceChildren();$('mini-game-list').replaceChildren();const acts=source.boxscores || source.sample_boxscores || [];const records=acts.filter(s=>s.milo?.length===1).map(s=>{const g=source.games.find(g=>String(g.IdPartidoNotificacion)===s.id);return {...s.milo[0],date:g?.Fecha,id:s.id,minutos:s.milo[0].milisegundos_jugados==null?null:Number(s.milo[0].milisegundos_jugados)/60000};}).filter(r=>r.date).sort((a,b)=>a.date.split('/').reverse().join('-').localeCompare(b.date.split('/').reverse().join('-')));
$('mini-source-date').textContent=`Dato CABB · ${source.games.length} partidos terminados del equipo · ${records.length} actas individuales consultadas · actualizado ${new Date(source.checked_at).toLocaleString('es-AR',{timeZone:'America/Buenos_Aires',hourCycle:'h23'})}`;
const metrics=[['puntos','Puntos por partido'],['minutos','Minutos por partido'],['faltascometidas','Faltas cometidas por partido'],['faltasrecibidas','Faltas recibidas por partido'],['valoracion','Valoración CABB por partido']];
const average=key=>averageMini(records,key);
for(const [key,label] of metrics){const card=node('section',null,$('mini-stat-summary'));card.className='tip';node('h3',label,card);const value=average(key);node('p',value==null?'Sin datos':value.toFixed(1),card).className='metric-value';node('small',`${records.length} actas disponibles · muestra consultada`,card);}
node('p','La valoración es el cálculo recibido de CABB con los conteos registrados en Mini; no es una evaluación completa de tus habilidades.',$('mini-stat-summary')).className='muted';
const games=[...source.games].sort((a,b)=>a.Fecha.split('/').reverse().join('-').localeCompare(b.Fecha.split('/').reverse().join('-'))).reverse();
for(const g of games){const home=g.NombreEquipoLocal==='QUILMES ATLETICO CLUB',rival=home?g.NombreEquipoVisitante:g.NombreEquipoLocal;const detail=node('details',null,$('mini-game-list'));node('summary',g.Fecha+' · '+rival,detail);const result=g.Resultados || {};node('p',`Resultado del equipo: ${home?result.ResultadoLocal:result.ResultadoVisitante}–${home?result.ResultadoVisitante:result.ResultadoLocal}`,detail);const row=records.find(r=>r.id===String(g.IdPartidoNotificacion));if(row){node('p',`Dato CABB: ${row.puntos ?? '—'} puntos · ${row.tiempo_jugado ?? '—'} minutos · ${row.valoracion ?? '—'} valoración`,detail);node('p',`Faltas: ${row.faltascometidas ?? '—'} cometidas · ${row.faltasrecibidas ?? '—'} recibidas`,detail);node('p',`Tiros: dobles ${row.canasta2p ?? '—'}/${row.tiro2p ?? '—'} · libres ${row.canasta1p ?? '—'}/${row.tiro1p ?? '—'}`,detail);}else node('p','Sin acta individual consultada para este partido.',detail);}
const evolution=()=>{const key=$('mini-evolution-metric').value,chart=$('mini-evolution-chart');chart.replaceChildren();const known=records.filter(r=>r[key]!=null && Number.isFinite(Number(r[key]))),max=Math.max(1,...known.map(r=>Math.abs(Number(r[key]))));for(const r of known){const line=node('div',null,chart);line.style.cssText='display:grid;grid-template-columns:95px 1fr 50px;gap:10px;align-items:center;margin:9px 0';node('span',r.date,line);const track=node('div',null,line);track.style.cssText='height:14px;background:#173048;border-radius:6px';const bar=node('div',null,track);bar.style.cssText=`height:100%;width:${Math.abs(Number(r[key]))/max*100}%;background:${Number(r[key])<0?'#c4b5fd':'#fb923c'};border-radius:6px`;node('strong',Number(r[key]).toFixed(key==='minutos'?1:0),line);}
$('mini-evolution-summary').replaceChildren();node('p',`${known.length} registros de ${records.length} actas consultadas. Compará los partidos con su contexto, sin tomar un número como una nota personal.`,$('mini-evolution-summary')).className='muted';if(records.length>=10){const recent=averageMini(records.slice(-5),key),previous=averageMini(records.slice(-10,-5),key);node('p',previous==null || recent==null ? 'No hay datos completos para comparar los dos bloques.' : `Cinco anteriores: ${previous.toFixed(1)} · últimos cinco: ${recent.toFixed(1)}. El cambio se conversa con el coach junto con la participación y los rivales.`,$('mini-evolution-summary'));}};$('mini-evolution-metric').addEventListener('change',evolution);evolution();
$('mini-coach-data').textContent=`Hay ${records.length} actas individuales para conversar: ${average('puntos')?.toFixed(1) ?? '—'} puntos y ${average('minutos')?.toFixed(1) ?? '—'} minutos por partido en esta muestra. Podemos revisar cómo participaste, en qué situaciones aparecen las faltas y qué acción te gustaría practicar. La elección del desafío se acuerda con tu coach.`;
$('mini-data-limit').textContent='Rebotes, asistencias y recuperos no se usan para construir tu perfil porque todavía no confirmamos su cobertura de registro en Mini. La valoración se muestra como dato CABB, con esa limitación.';
}catch(e){$('mini-source-date').textContent='No se pudieron cargar los partidos oficiales. Reintentá más tarde.';}
}
await renderOfficial();
}
if(typeof module!=='undefined')module.exports={playerMatches,mergeEntries,validPractice,averageMini};
if(typeof document!=='undefined')document.addEventListener('DOMContentLoaded',load);
})();
