/* Acceso del jugador: correo permanente y formulario de contraseña temporal. */
(function(){
 async function invoke(body){const {data,error}=await supa.functions.invoke('nextlevel-onboard',{body});if(error){let message=error.message;try{const response=await error.context?.json();message=response?.error || message;}catch(_){}throw Error(message);}if(data?.error)throw Error(data.error);return data;}
 function mount(player,host){const node=(tag,text,parent)=>{const e=document.createElement(tag);if(text!=null)e.textContent=text;parent.append(e);return e;};const panel=node('section',null,host);panel.style.cssText='padding:16px;margin-top:16px;border:1px solid #35516c;border-radius:12px';node('h3','Acceso jugador / padre',panel).style.cssText='color:#38bdf8;font-size:17px';if(!player.user_id){node('p','Este perfil todavía no tiene una cuenta vinculada.',panel);return;}
 const email=node('p','Correo: cargando…',panel);email.style.cssText='font-size:16px;font-weight:700;overflow-wrap:anywhere;color:#e2e8f0';
 const open=node('button','Cambiar contraseña',panel);open.className='btn-sm';open.type='button';open.disabled=true;const status=node('p',null,panel);status.setAttribute('role','status');status.style.cssText='font-size:14px;line-height:1.5';let busy=false,account=null;
 async function loadAccount(){if(busy)return;busy=true;open.disabled=true;try{const data=await invoke({action:'player-account',playerId:player.id});if(!panel.isConnected)return;if(!data?.email)throw Error('No se encontró el correo vinculado.');account=data;email.textContent='Correo de acceso: '+account.email;status.textContent='Usá este correo para iniciar sesión.';open.textContent='Cambiar contraseña';}catch(e){email.textContent='Correo de acceso: no disponible';status.textContent=e.message;open.textContent='Reintentar cargar cuenta';}finally{busy=false;open.disabled=false;}}
 function showForm(){if(busy)return;open.hidden=true;status.textContent='';const form=node('form',null,panel);node('p','Definí una contraseña nueva y compartila con el jugador/padre. No se envía un correo automático.',form).style.fontSize='14px';
 const field=text=>{const label=node('label',text,form);label.style.cssText='display:block;margin:12px 0;font-size:15px';const input=node('input',null,label);input.type='password';input.required=true;input.minLength=8;input.maxLength=128;input.autocomplete='new-password';input.style.cssText='display:block;width:100%;margin-top:6px;padding:10px;background:#102035;color:#e2e8f0;border:1px solid #35516c;border-radius:8px;font:inherit';return input;};const password=field('Contraseña nueva'),confirm=field('Repetir contraseña');
 const submit=node('button','Guardar contraseña nueva',form);submit.className='btn-sm';submit.type='submit';const cancel=node('button','Cancelar',form);cancel.className='btn-sm';cancel.type='button';cancel.style.marginLeft='8px';
 const close=()=>{password.value=confirm.value='';form.remove();open.hidden=false;};cancel.onclick=()=>{if(busy)return;close();status.textContent='';};
 form.onsubmit=async event=>{event.preventDefault();if(busy || !form.reportValidity())return;if(password.value!==confirm.value){status.textContent='Las contraseñas no coinciden.';confirm.focus();return;}busy=true;submit.disabled=cancel.disabled=true;status.textContent='Actualizando contraseña…';try{const result=await invoke({action:'set-player-password',playerId:player.id,password:password.value});if(result?.ok!==true || result?.verified!==true)throw Error('El servidor no verificó el acceso. Actualizá la función nextlevel-onboard y repetí el cambio.');close();status.textContent='✅ Contraseña actualizada y acceso verificado. Ya puede ingresar con la nueva.';}catch(e){status.textContent='No se pudo cambiar: '+e.message;}finally{busy=false;submit.disabled=cancel.disabled=false;}};
 }
 open.onclick=()=>account?showForm():loadAccount();loadAccount();
 }
 window.NextLevelAccount={mount};
})();
