const assert=require('node:assert/strict'),e=require('./nextlevel_gradual_goals.js');
const rows=Array.from({length:5},(_,i)=>({cabb_partido_id:String(i+1),fecha:'2026-09-0'+(i+1),source:'cabb_api',torneo:'AFMB',minutos:8,ast:i<3?1:0,stl:0,reb_tot:3,to_perdidas:2,tl_in:1,tl_att:2,t2_in:2,t2_att:4}));
const now='2026-09-05T15:00:00Z',g=e.create('ast','AFMB',rows,now,{goalMode:'game_block_v2'});
assert.equal(g.baseline.value,.6);assert.equal(g.baseline.total,3);assert.equal(g.baseline.games,5);assert.equal(g.baseline.expectedInBlock,1.2);assert.equal(g.target,2);
assert.equal(e.create('ast','AFMB',rows.map(r=>({...r,ast:3})),now,{goalMode:'game_block_v2'}).target,7);
assert.equal(e.create('ast','AFMB',rows.map(r=>({...r,ast:0})),now,{goalMode:'game_block_v2'}).target,1);
const next=[6,7,8].map(n=>({...rows[0],cabb_partido_id:String(n),fecha:'2026-09-0'+n,ast:n===8?100:1}));
assert.equal(e.evaluate(g,[...rows,next[0]],now).status,'active');
const won=e.evaluate(g,[...rows,...next],now);assert.equal(won.status,'achieved');assert.equal(won.evaluation.value,2);assert.deepEqual(won.achievements[0].gameIds,['6','7']);
assert.equal(e.evaluate(g,[...rows,...next.map(r=>({...r,ast:r.cabb_partido_id==='6'?2:0}))],now).status,'achieved');
assert.equal(e.evaluate(g,[...rows,{...next[0],ast:null},next[1]],now).status,'active');
const failed=e.evaluate(g,[...rows,...next.map(r=>({...r,ast:r.cabb_partido_id==='8'?100:0}))],now);assert.equal(failed.status,'review');
const retry=e.retry(failed,[...rows,...next],now);assert.equal(retry.target,2);assert.equal(retry.status,'active');assert.equal(retry.attempts.length,1);assert.equal(e.evaluate(retry,[...rows,...next],now).evaluation.games,0);
const advanced=e.advance(won,[...rows,...next.slice(0,2)],now);assert.equal(advanced.target,3);assert.equal(advanced.achievements.length,1);assert.equal(e.evaluate(advanced,[...rows,...next.slice(0,2)],now).evaluation.games,0);assert.ok(e.advance(won,[...rows,...next],now).target>3);
const minute=e.create('minutes','AFMB',rows,now,{goalMode:'game_block_v2',participationCap:20,participationCategory:'U13'});assert.equal(minute.target,20);
const losses=e.create('losses','AFMB',rows,now,{goalMode:'game_block_v2'});assert.equal(losses.target,3);assert.equal(e.evaluate(losses,[...rows,...next.slice(0,2).map(r=>({...r,to_perdidas:1}))],now).status,'achieved');
const legacy=e.create('ast','AFMB',rows,now);const migrated=e.migrate({...legacy,achievements:[{id:'old'}]},rows,now,{goalMode:'game_block_v2'});assert.equal(migrated.mode,'game_block_v2');assert.equal(migrated.target,2);assert.equal(migrated.achievements.length,1);assert.equal(migrated.previousCriteria.target,legacy.target);
assert.equal(e.blockBaseline(rows.map(r=>({...r,ast:null})),'ast').ready,false);
assert.match(e.blockDescription('ast',2),/en total entre los próximos 2 partidos/);
console.log('OK Base clara, metas adaptadas, suma entre 2 partidos, sin media ni ventanas móviles, datos faltantes, reintentos, etapas y migración.');
