const assert=require('node:assert/strict'),catalog=require('./nextlevel_goal_catalog.js'),engine=require('./nextlevel_gradual_goals.js');
assert.deepEqual(catalog.recommendations({areas:['Defensa']}),['stl','practice_defense']);
assert.deepEqual(catalog.recommendations({technicalAreas:['Defensa']},{mini:true,category:'U11',minutes:8}),['minutes','practice_defense']);
assert.deepEqual(catalog.recommendations({areas:['Tiro libre']}),['tl','practice_free']);
assert.ok(!catalog.recommendations({areas:['Defensa']}).includes('tl'));
assert.ok(catalog.recommendations({areas:['Mental'],mentalAreas:['Seguir después de un error']}).includes('practice_reset'));
assert.ok(!catalog.recommendations({areas:['Mental'],mentalAreas:['Seguir después de un error']}).includes('practice_mental'));
assert.deepEqual(catalog.recommendations({}),[]);
for(const [base,target] of [[4,5],[8,10],[12,14],[18,19],[19.5,20],[20,null]])assert.equal(engine.target('minutes',base,{participationCap:20}),target);
assert.equal(catalog.participationReference('U11'),20);assert.equal(catalog.participationReference('U13 Femenino'),20);assert.equal(catalog.participationReference('MINI MASCULINO'),20);
assert.equal(catalog.participationReference('U15'),null);assert.equal(catalog.participationReference('U17',30),30);assert.equal(catalog.participationReference('U19',35),35);assert.equal(catalog.participationReference('',30),null);
assert.equal(catalog.participationReference('U13',30),20);
assert.ok(!catalog.recommendations({areas:['Defensa']},{category:'U15',minutes:8}).includes('minutes'));
assert.ok(catalog.recommendations({areas:['Defensa']},{category:'U17',minutes:22,coachReference:30}).includes('minutes'));
assert.equal(engine.target('minutes',22,{participationCap:30}),23);assert.equal(engine.target('minutes',29.5,{participationCap:30}),30);assert.equal(engine.target('minutes',22),null);
const start='2026-10-01T10:00:00Z',goal=engine.create('practice_defense','Práctica personal',[],start);
assert.equal(goal.target,3);
const entries=[1,2,3].map(n=>({id:String(n),source:'player_training',date:'2026-10-0'+n,createdAt:'2026-10-0'+n+'T15:00:00Z',areas:['Defensa']}));
assert.equal(engine.evaluate(goal,[],'2026-10-07T12:00:00Z',entries.slice(0,2)).status,'active');
const won=engine.evaluate(goal,[],'2026-10-07T12:00:00Z',entries);assert.equal(won.status,'achieved');assert.equal(won.achievements[0].source,'player_training');assert.equal(won.achievements[0].gameIds.length,0);
assert.equal(engine.evaluate(goal,[],'2026-10-07T12:00:00Z',entries.map(e=>({...e,date:'2026-10-01'}))).status,'active');
assert.equal(engine.evaluate(goal,[],'2026-10-07T12:00:00Z',entries.map(e=>({...e,areas:['Tiro']}))).status,'active');
assert.equal(engine.evaluate(goal,[],'2026-10-07T12:00:00Z',entries.map(e=>({...e,createdAt:'2026-09-30T12:00:00Z'}))).status,'active');
const next=engine.advance(won,[],'2026-10-07T12:00:00Z');assert.equal(next.target,4);assert.equal(engine.evaluate(next,[],'2026-10-07T13:00:00Z',entries).status,'active');
assert.equal(engine.evaluate(won,[],'2026-10-07T12:00:00Z',entries).achievements.length,1);
console.log('OK Preferencias individuales, Mini, participación, prácticas en días distintos, área correcta, etapas y logros separados de estadísticas.');
