const assert=require('node:assert/strict'),model=require('./nextlevel_coach_personalization.js'),engine=require('./nextlevel_gradual_goals.js');
const games=(minutes=8)=>Array.from({length:5},(_,i)=>({cabb_partido_id:String(i+1),fecha:'2026-09-0'+(i+1),source:'cabb_api',torneo:'AFMB',minutos:minutes,pts:3,stl:1,to_perdidas:1,ast:2,reb_tot:3,tl_in:6,tl_att:10,t2_in:4,t2_att:10,t3_in:2,t3_att:5}));
let count=0;function test(name,fn){fn();count++;console.log('OK '+name);}
test('U13: participación y defensa como prioridades',()=>{const m=model.analyze(games(8),{category:'U13',profile:{areas:['Defensa']}});assert.deepEqual(m.priorities.map(p=>p.metric),['minutes','practice_defense']);assert.equal(m.proposals.find(p=>p.metric==='minutes').target,20);assert.ok(!m.proposals.some(p=>p.metric==='tl'));});
test('U15 no recibe techo de 20',()=>{const m=model.analyze(games(22),{category:'U15',profile:{areas:['Defensa']}});assert.equal(m.reference,null);assert.ok(!m.proposals.some(p=>p.metric==='minutes'));assert.match(m.participation,/coach debe acordar/);});
test('U17 con referencia del coach puede superar 20',()=>{const m=model.analyze(games(22),{category:'U17',coachReference:30});assert.equal(m.proposals[0].target,46);});
test('Alcanzar referencia cambia la prioridad',()=>assert.ok(!model.analyze(games(20),{category:'U13',profile:{areas:['Defensa']}}).proposals.some(p=>p.metric==='minutes')));
test('Áreas elegidas producen recomendaciones diferentes',()=>{const m=model.analyze(games(20),{category:'U13',profile:{areas:['Tiro libre']}});assert.deepEqual(m.proposals.map(p=>p.metric),['tl','practice_free']);assert.equal(m.proposals[0].target,13);});
test('Muestras insuficientes quedan provisionales',()=>{const m=model.analyze(games().slice(0,3),{category:'U13',profile:{areas:['Tiro libre']}});assert.equal(m.proposals[0].ready,false);assert.equal(m.proposals[0].target,null);assert.match(m.proposals[0].evidence,/provisional/);});
test('Mini no atribuye cobertura de recuperos',()=>{const m=model.analyze(games(8),{mini:true,category:'U11',profile:{technicalAreas:['Defensa']}});assert.ok(!m.proposals.some(p=>p.metric==='stl'));assert.ok(!m.cards.some(c=>c[1]==='Recuperos'));});
test('Sin áreas no inventa una prioridad técnica',()=>assert.equal(model.analyze(games(20),{category:'U13'}).proposals.length,0));
test('Las metas activadas conservan prioridad',()=>{const goal=engine.create('tl','AFMB',games(20),'2026-10-01');const m=model.analyze(games(20),{category:'U13',profile:{areas:['Defensa']},goals:[goal]});assert.equal(m.priorities[0].metric,'tl');assert.equal(m.priorities[0].active,true);});
test('No mezcla metas de distintos torneos',()=>{const goal={...engine.create('tl','AFMB',games(20),'2026-10-01'),torneo:'Federal'};assert.equal(model.analyze(games(20),{category:'U13',goals:[goal]}).proposals.length,0);});
test('Logros de práctica no se presentan como habilidades',()=>{const g=engine.create('practice_defense','AFMB',games(20),'2026-10-01');g.achievements=[{id:'x',value:3,date:'2026-10-05'}];const m=model.analyze(games(20),{category:'U13',goals:[g]});assert.equal(m.achievements[0].source,'player_training');});
test('Después de cumplir, propone la misma etapa siguiente que Mi Plan',()=>{const g={...engine.create('practice_defense','AFMB',games(20),'2026-10-01'),status:'achieved',evaluation:{ready:true,value:3}};const m=model.analyze(games(20),{category:'U13',profile:{areas:['Defensa']},goals:[g]});assert.equal(m.proposals.find(p=>p.metric==='practice_defense').target,4);});
test('No cuenta no participación ni datos ausentes como cero',()=>{const rows=games(0);assert.equal(model.analyze(rows,{category:'U13'}).coverage,0);assert.equal(model.avg([{minutos:null}],'minutos'),null);assert.equal(model.avg([{minutos:false}],'minutos'),null);});
test('Recuperos por minuto para comparar cambios de participación',()=>{const rows=[...games(10),...games(20).map((g,i)=>({...g,cabb_partido_id:String(i+6),fecha:'2026-09-'+String(i+6).padStart(2,'0'),stl:2}))];const trend=model.analyze(rows,{category:'U13'}).trend.find(t=>t.label==='recuperos');assert.equal(trend.before,2);assert.equal(trend.recent,2);assert.equal(trend.unit,'por 20 minutos');});
console.log(`${count} pruebas del análisis personalizado pasaron.`);
