// Coach onboarding and official synchronization. Service credentials remain server-side.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";
const url=Deno.env.get('SUPABASE_URL')!,serviceKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const db=createClient(url,serviceKey),cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,apikey,content-type,x-client-info'};
const answer=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{...cors,'Content-Type':'application/json'}});
const norm=(s:unknown)=>String(s || '').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim();
function playerNameKey(s:unknown){const value=norm(s).replace(/\s+/g,' '),parts=value.split(',').map(v=>v.trim());return parts.length===2 && parts.every(Boolean)?parts.sort().join(','):value;}
function samePlayerName(a:unknown,b:unknown){return playerNameKey(a)===playerNameKey(b);}
const teamName=(s:unknown)=>String(s || '').replace(/\s+/g,' ').trim().toUpperCase();
function assertBoxscoreFixture(r:any,g:any){if(r.partido?.estado_partido!=='FINALIZADO' || !teamName(g.NombreEquipoLocal) || !teamName(g.NombreEquipoVisitante) || teamName(r.partido.local)!==teamName(g.NombreEquipoLocal) || teamName(r.partido.visitante)!==teamName(g.NombreEquipoVisitante))throw Error('Boxscore no corresponde al fixture · '+g.IdPartidoNotificacion+' · '+g.Fecha);}
const needed=(s:unknown)=>{if(typeof s!=='string' || !s.trim() || s.length>250)throw Error('Datos incompletos');return s.trim();};
const check=(r:any,label:string)=>{if(r?.resultado!=='correcto')throw Error('CABB '+label+': '+(r?.error || 'respuesta inválida'));return r;};
class Cabb{
 device='';key='';
 async post(path:string,args:Record<string,unknown>){const body=new URLSearchParams({...Object.fromEntries(Object.entries(args).map(([k,v])=>[k,String(v)])),...(this.device?{id_dispositivo:this.device,key:this.key}:{})});const r=await fetch('https://appaficioncabb.indalweb.net/'+path,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','User-Agent':'Dalvik/2.1.0 (Linux; Android 10)'},body,signal:AbortSignal.timeout(25000)});if(!r.ok)throw Error('CABB HTTP '+r.status);const data=await r.json();if(data.key)this.key=data.key;return data;}
 async init(){const r=check(await this.post('dispositivo.ashx',{accion:'registrar',uid:crypto.randomUUID(),plataforma:'android',tipo_dispositivo:'mobile',version:'40044'}),'registro');this.device=r.id_dispositivo;this.key=r.key;}
 async teams(text:string){const all:any[]=[];for(let skip=0;skip<1000;skip+=20){const r=check(await this.post('v2/busqueda.ashx',{accion:'buscarEquipo',texto:text,skip}),'equipos');all.push(...r.equipos || []);if((r.equipos || []).length<20)break;}return all;}
 async team(spec:any){const matches=(await this.teams(spec.club)).filter(t=>t.Nombre===spec.club && t.Categoria===spec.categoryName && t.Competicion===spec.competition && t.Delegacion===spec.federation && String(t.Temporada)===String(spec.season));if(matches.length!==1)throw Error('Equipo/categoría ambiguo; repetí la búsqueda.');return matches[0];}
 async roster(spec:any){const t=await this.team(spec);const r=check(await this.post('v2/equipo.ashx',{accion:'jugadores',id_equipo:t.Id}),'plantel');return r.misjugadores || [];}
 async category(spec:any){const found:any[]=[];for(let skip=0;skip<1000;skip+=20){const r=check(await this.post('v2/busqueda.ashx',{accion:'buscarCategoria',texto:spec.categoryName,skip}),'categorías');found.push(...(r.categorias || []).filter((c:any)=>c.NombreCategoria===spec.categoryName && c.NombreCompeticion===spec.competition && c.NombreDelegacion===spec.federation));if((r.categorias || []).length<20)break;}const unique=[...new Map(found.map(c=>[c.Id,c])).values()];if(unique.length!==1)throw Error('Categoría canónica ambigua o ausente');return unique[0];}
 async games(spec:any){const category=await this.category(spec),phases=check(await this.post('v2/categoria.ashx',{accion:'fasesGrupos',id_categoria_competicion:category.Id}),'fases'),games=new Map<string,any>();for(const phase of phases.listaFasesGrupo || [])for(const group of phase.Grupos || []){const r=check(await this.post('v2/categoria.ashx',{accion:'horariosJornadas',id_categoria_competicion:category.Id,id_fase:phase.IdFase,id_grupo:group.IdGrupo}),'fixture');for(const g of r.partidos || [])if(g.Estado==='Terminado' && [g.NombreEquipoLocal,g.NombreEquipoVisitante].includes(spec.club) && g.Fecha.endsWith('/'+spec.season)){const id=String(g.IdPartidoNotificacion);if(!/^\d+$/.test(id))throw Error('Fixture sin ID estable');const old=games.get(id);if(old && JSON.stringify(old.Resultados)!==JSON.stringify(g.Resultados))throw Error('Fixture contradictorio');games.set(id,{...g,fase:phase.NombreFase});}}return [...games.values()].sort((a,b)=>isoDate(a.Fecha).localeCompare(isoDate(b.Fecha)));}
}
function isoDate(s:string){const [d,m,y]=s.split('/');if(!d || !m || !y)throw Error('Fecha CABB inválida');return y+'-'+m+'-'+d;}
function num(v:unknown){if(v==null || v==='' || typeof v==='boolean')return null;const n=Number(v);return Number.isFinite(n)?n:null;}
function rowsFor(p:any,g:any,config:any,tournament:any,stamp:string){const home=g.NombreEquipoLocal===tournament.club,score=num(g.Resultados?.[home?'ResultadoLocal':'ResultadoVisitante']),against=num(g.Resultados?.[home?'ResultadoVisitante':'ResultadoLocal']);if(score==null || against==null)throw Error('Resultado ausente');const row:any={player_id:config.playerId,cabb_partido_id:String(g.IdPartidoNotificacion),fecha:isoDate(g.Fecha),rival:g[home?'NombreEquipoVisitante':'NombreEquipoLocal'],torneo:tournament.label,fase:g.fase,es_local:home,resultado_eq:score+'-'+against,ganado:score>against,pts:num(p.puntos),minutos:num(p.milisegundos_jugados)==null?null:Number(p.milisegundos_jugados)/60000,source:'cabb_api',synced_at:stamp};
 for(const [key,k] of [['tl','1'],['t2','2'],['t3','3']]){row[key+'_in']=num(p['canasta'+k+'p']);row[key+'_att']=num(p['tiro'+k+'p']);if(row[key+'_in']!=null && row[key+'_att']!=null && !(row[key+'_in']>=0 && row[key+'_att']>=row[key+'_in']))throw Error('Intentos no reconciliados');}
 if([row.tl_in,row.t2_in,row.t3_in,row.pts].every(n=>n!=null) && row.pts!==row.tl_in+2*row.t2_in+3*row.t3_in)throw Error('Puntos no reconciliados');
 row.tc_in=row.t2_in==null || row.t3_in==null?null:row.t2_in+row.t3_in;row.tc_att=row.t2_att==null || row.t3_att==null?null:row.t2_att+row.t3_att;
 for(const [key,raw] of [['reb_tot','rebotes'],['reb_def','rebotedefensivo'],['reb_of','reboteofensivo'],['ast','asistencias'],['stl','recuperaciones'],['blk','taponescometidos'],['to_perdidas','perdidas'],['faltas','faltascometidas'],['val','valoracion']])row[key]=(config.template==='mini' && !['faltas','val'].includes(key))?null:num(p[raw]);return row;
}
function extractShots(events:any[],box:any,p:any,home:boolean){
 const side=home?'local':'visitante',shots=new Map<string,any>();
 for(const e of events){if(String(e.eliminado).toLowerCase()==='true' || String(e.equipo_id)!==String(box.partido['id'+side]) || String(e.dorsal)!==String(p.dorsal) || !['CANASTA-2P','CANASTA-3P','TIRO2-FALLADO','TIRO3-FALLADO'].includes(e.accion_tipo))continue;
  const id=String(e.autoincremental_id);if(!/^\d+$/.test(id))throw Error('Tiro sin ID');const shot=Object.fromEntries(['autoincremental_id','accion_tipo','numero_periodo','tiempo_partido','posicion_x','posicion_y','zona'].map(k=>[k,e[k] ?? null]));if(shots.has(id) && JSON.stringify(shots.get(id))!==JSON.stringify(shot))throw Error('Tiro contradictorio');shots.set(id,shot);
 }
 const list=[...shots.values()],expected=num(p.tiro2p)==null || num(p.tiro3p)==null?null:Number(p.tiro2p)+Number(p.tiro3p),made=num(p.canasta2p)==null || num(p.canasta3p)==null?null:Number(p.canasta2p)+Number(p.canasta3p);
 return {shots:list,expected_attempts:expected,expected_made:made,matched:expected!=null && made!=null && list.length===expected && list.filter(s=>s.accion_tipo.startsWith('CANASTA')).length===made,coordinate_count:list.filter(s=>num(s.posicion_x)!=null && num(s.posicion_y)!=null && (Number(s.posicion_x)!==0 || Number(s.posicion_y)!==0)).length};
}
async function checkedWrite(table:string,data:any,conflict:string){const {error}=await db.from(table).upsert(data,{onConflict:conflict});if(error)throw error;}
const clubIdentity=(s:unknown)=>norm(s).replace(/\b(CLUB|SOCIAL|Y|DEPORTIVO|DEPORTIVA|DEP|ATLETICO)\b/g,' ').replace(/[.]/g,' ').replace(/\s+/g,' ').trim();
function federalCandidate(t:any,config:any,season:string){const stages:Record<string,RegExp>={U13:/INFANTIL|U13/,U15:/CADET|U15/,U17:/JUVENIL|U17/,U19:/U19/,U21:/U21/,Mayores:/MAYORES/};const stage=stages[config.category];return !!stage && String(t.Temporada)===season && /FEDERAL/.test(norm(t.Categoria)) && stage.test(norm(t.Categoria)) && clubIdentity(t.Nombre)===clubIdentity(config.club);}
async function discoverFederal(c:Cabb,config:any,season:string){if(config.template==='mini')return [];const teams=await c.teams(clubIdentity(config.club)),extra:any[]=[];
 for(const t of teams.filter(t=>federalCandidate(t,config,season))){const spec={club:t.Nombre,categoryName:t.Categoria,competition:t.Competicion,federation:t.Delegacion,season,label:'Federal CABB'};if(config.tournaments.some((old:any)=>old.club===spec.club && old.categoryName===spec.categoryName && old.competition===spec.competition && old.federation===spec.federation))continue;const roster=await c.roster(spec),matches=roster.filter((p:any)=>samePlayerName(p.Nombre,config.cabbName));if(matches.length>1)throw Error('Identidad ambigua en plantel Federal');if(matches.length===1 && Number(matches[0].PartidosJugados)>0){await c.category(spec);extra.push(spec);}}
 if(extra.length>1)throw Error('Más de un equipo Federal coincide; revisá la vinculación del torneo.');return extra;}
async function syncPlayer(playerId:string,season:string){
 const {data:setting,error}=await db.from('player_data').select('data').eq('player_id',playerId).eq('module','player_season_v1:'+season).maybeSingle();if(error)throw error;if(!setting?.data?.tournaments?.length)throw Error('Este perfil no tiene equipo y torneo vinculados en '+season+'. Si hay otro perfil con el mismo nombre, seleccioná el que vinculaste durante el alta.');const config={...setting.data,playerId},c=new Cabb();await c.init();const extra=await discoverFederal(c,config,season);config.tournaments=[...config.tournaments,...extra];let latestDorsal:number|null=null,latestDorsalDate='';const stamp=new Date().toISOString(),allRows:any[]=[],miniGames:any[]=[],miniActs:any[]=[],teamGames:any[]=[],shotGames:any[]=[];
 for(const t of config.tournaments){const fixtures=await c.games({...t,season}),rows:any[]=[];
 for(const g of fixtures){const r=check(await c.post('v2/envivo/estadisticas.ashx',{accion:'estadisticasPartido',id_partido:g.IdPartido}),'boxscore');assertBoxscoreFixture(r,g);const home=g.NombreEquipoLocal===t.club,players=r.estadisticas?.[home?'estadisticasequipolocal':'estadisticasequipovisitante'];if(!Array.isArray(players))throw Error('Boxscore ausente');const matches=players.filter((p:any)=>samePlayerName(p.nombre,config.cabbName));if(matches.length>1)throw Error('Jugador duplicado en acta');const personal=matches.filter((p:any)=>Number(p.milisegundos_jugados)>0 || ['puntos','rebotes','asistencias','faltascometidas'].some(k=>Number(p[k])>0));if(personal.length)rows.push(rowsFor(personal[0],g,config,t,stamp));if(personal.length){const dorsal=num(personal[0].dorsal),date=isoDate(g.Fecha);if(dorsal!=null && Number.isInteger(dorsal) && dorsal>=0 && dorsal<=99 && date>=latestDorsalDate){latestDorsal=dorsal;latestDorsalDate=date;}}
 if(config.template!=='mini' && personal.length){const record:any={id:String(g.IdPartidoNotificacion),tournament:t.label,date:g.Fecha,shots:[],matched:false};try{const pbp=check(await c.post('v2/envivo/partido.ashx',{id_partido:g.IdPartido}),'PBP');if(!Array.isArray(pbp.envivo?.historialacciones))throw Error('PBP no disponible');Object.assign(record,extractShots(pbp.envivo.historialacciones,r,personal[0],home));}catch(e){record.error=e.message;}shotGames.push(record);}
 const sanitized=personal.map((p:any)=>Object.fromEntries(Object.entries(p).filter(([k])=>!['componente_id','id','foto'].includes(k.toLowerCase()))));miniGames.push(Object.fromEntries(Object.entries(g).filter(([k])=>['IdPartidoNotificacion','Fecha','NombreEquipoLocal','NombreEquipoVisitante','Resultados','Estado'].includes(k))));miniActs.push({id:String(g.IdPartidoNotificacion),player_rows:sanitized});
 teamGames.push({id:String(g.IdPartidoNotificacion),date:isoDate(g.Fecha),tournament:t.label,available:true,players:players.filter((p:any)=>norm(p.nombre)!=='TOTALES' && (Number(p.milisegundos_jugados)>0 || ['puntos','rebotes','asistencias','faltascometidas'].some(k=>Number(p[k])>0))).map((p:any)=>({name:samePlayerName(p.nombre,config.cabbName)?config.cabbName:p.nombre,pts:num(p.puntos),reb_tot:num(p.rebotes),stl:num(p.recuperaciones),blk:num(p.taponescometidos),ast:num(p.asistencias),fouls_received:num(p.faltasrecibidas),to_perdidas:num(p.perdidas),faltas:num(p.faltascometidas),val:num(p.valoracion)}))});}
 if(!fixtures.length)throw Error('Sin partidos terminados; no se sustituye la temporada por ceros.');
 const roster=await c.roster({...t,season}),official=roster.filter((p:any)=>samePlayerName(p.Nombre,config.cabbName));if(official.length!==1)throw Error('Jugador ausente/ambiguo en el plantel');const expected=num(official[0].PartidosJugados);if(expected!=null && expected!==rows.length)throw Error(`Cobertura incompleta: ${rows.length}/${expected} actas. No se actualiza el resumen.`);
 allRows.push(...rows);const avg=(key:string)=>rows.length && rows.every(r=>r[key]!=null)?rows.reduce((n,r)=>n+r[key],0)/rows.length:null;
 if(rows.length)await checkedWrite('game_log',rows,'player_id,cabb_partido_id');
 const stats:any={player_id:playerId,season,tournament:t.label,pj:rows.length,ppg:avg('pts'),min_pg:avg('minutos'),val_pg:avg('val'),updated_at:stamp};if(config.template!=='mini')Object.assign(stats,{rpg:avg('reb_tot'),apg:avg('ast'),spg:avg('stl'),bpg:avg('blk')});await checkedWrite('stats_seasons',stats,'player_id,season,tournament');
 }
 if(config.template==='mini')await checkedWrite('player_data',{player_id:playerId,module:'cabb_mini_official_v1:'+season,data:{season,club:config.club,category:config.category,checked_at:stamp,games:miniGames,boxscores:miniActs},updated_at:stamp},'player_id,module');
 if(config.template!=='mini')await checkedWrite('player_data',{player_id:playerId,module:'cabb_shots_v1:'+season,data:{season,player_name:config.cabbName,generated_at:stamp,games:shotGames},updated_at:stamp},'player_id,module');
 await checkedWrite('player_data',{player_id:playerId,module:'cabb_team_v1:'+season,data:{season,generated_at:stamp,games:teamGames},updated_at:stamp},'player_id,module');
 const {data:dorsalOverride,error:dorsalError}=await db.from('player_data').select('data').eq('player_id',playerId).eq('module','profile_dorsal_v1').maybeSingle();if(dorsalError)throw dorsalError;
 const chosen=dorsalOverride?.data?.dorsal ?? latestDorsal ?? setting.data.dorsal ?? null;
 if(chosen!=null){const {error:playerError}=await db.from('players').update({dorsal:chosen}).eq('id',playerId);if(playerError)throw playerError;}
 if(extra.length || latestDorsal!=null)await checkedWrite('player_data',{player_id:playerId,module:'player_season_v1:'+season,data:{...setting.data,tournaments:config.tournaments,dorsal:chosen,cabbDorsal:latestDorsal},updated_at:stamp},'player_id,module');
 await checkedWrite('player_data',{player_id:playerId,module:'sync_status_v1:'+season,data:{status:'complete',games:allRows.length,updatedAt:stamp},updated_at:stamp},'player_id,module');return {games:allRows.length,updatedAt:stamp};
}
async function verifyChangedPassword(user:any,password:string){const response=await fetch(url+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:serviceKey,'Content-Type':'application/json'},body:JSON.stringify({email:user.email,password}),signal:AbortSignal.timeout(15000)});const result=await response.json();if(!response.ok || result.user?.id!==user.id)throw Error('Supabase aceptó el cambio, pero no confirmó el inicio de sesión con la contraseña nueva ('+(result.error_code || 'cuenta no coincidente')+'). No se comprobó el acceso.');}
async function linkedPlayerAccount(database:any,playerId:string,coachEmail:string){if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(playerId))throw Error('Jugador inválido');const {data:player,error}=await database.from('players').select('id,name,user_id').eq('id',playerId).maybeSingle();if(error)throw error;if(!player?.user_id)throw Error('Este jugador no tiene una cuenta vinculada.');const {data:account,error:accountError}=await database.auth.admin.getUserById(player.user_id);if(accountError)throw accountError;if(!account?.user?.email)throw Error('No se encontró el correo de la cuenta vinculada.');if(account.user.email.toLowerCase()===coachEmail.toLowerCase())throw Error('Esta opción es para cuentas de jugador/padre.');return {player,user:account.user};}
async function changePlayerPassword(database:any,playerId:string,password:unknown,coachEmail:string,verify:any=verifyChangedPassword){if(typeof password!=='string' || password.length<8 || password.length>128)throw Error('La contraseña debe tener entre 8 y 128 caracteres.');const {player,user}=await linkedPlayerAccount(database,playerId,coachEmail);const {error}=await database.auth.admin.updateUserById(user.id,{password});if(error)throw error;await verify(user,password);return {ok:true,verified:true,playerId:player.id,email:user.email};}
async function changePlayerEmail(database:any,playerId:string,emailValue:unknown,coachEmail:string){const email=typeof emailValue==='string'?emailValue.trim().toLowerCase():'';if(email.length>254 || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw Error('Revisá el correo nuevo.');if(email===coachEmail.toLowerCase())throw Error('Usá un correo de jugador/padre, distinto al del coach.');const {player,user}=await linkedPlayerAccount(database,playerId,coachEmail);const {data,error}=await database.auth.admin.updateUserById(user.id,{email,email_confirm:true});if(error)throw error;if(data?.user?.id!==user.id || data.user.email?.toLowerCase()!==email)throw Error('Supabase no confirmó la corrección del correo.');return {ok:true,playerId:player.id,email};}
Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});
 try{
 const token=req.headers.get('Authorization')?.replace(/^Bearer /,'') || '';const service=token===serviceKey;
 if(!service){const {data,error}=await db.auth.getUser(token);if(error || data?.user?.email!==(Deno.env.get('NEXTLEVEL_COACH_EMAIL') || 'coach@nextlevel.com'))return answer({error:'Acceso del coach requerido'},403);}
 const body=await req.json();if(body.action==='sync'){needed(body.playerId);if(!/^20\d{2}$/.test(body.season))throw Error('Temporada inválida');return answer(await syncPlayer(body.playerId,body.season));}
 if(body.action==='player-account' || body.action==='set-player-password' || body.action==='set-player-email'){if(service)return answer({error:'Entrá con la cuenta del coach para administrar contraseñas.'},403);const coachEmail=Deno.env.get('NEXTLEVEL_COACH_EMAIL') || 'coach@nextlevel.com';if(body.action==='player-account'){const {user,player}=await linkedPlayerAccount(db,needed(body.playerId),coachEmail);return answer({playerId:player.id,email:user.email});}if(body.action==='set-player-email')return answer(await changePlayerEmail(db,needed(body.playerId),body.email,coachEmail));return answer(await changePlayerPassword(db,needed(body.playerId),body.password,coachEmail));}
 const c=new Cabb();await c.init();
 if(body.action==='teams'){const teams=await c.teams(needed(body.query));return answer({teams:teams.filter(t=>String(t.Temporada)===body.season).map(t=>({club:t.Nombre,categoryName:t.Categoria,competition:t.Competicion,federation:t.Delegacion,season:String(t.Temporada)}))});}
 if(body.action==='roster'){const players=await c.roster(body.team);return answer({players:players.map((p:any)=>({name:p.Nombre,pj:p.PartidosJugados,dorsal:p.Dorsal ?? null}))});}
 if(body.action!=='create')throw Error('Acción desconocida');
 const {team}=body,season=String(team.season),displayName=needed(body.name),cabbName=needed(body.cabbName),category=needed(body.category),email=needed(body.email).toLowerCase();if(!/^20\d{2}$/.test(season) || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw Error('Temporada o correo inválido');
 const template=category==='Mini U11'?'mini':['U13','U15','U17','U19','U21','Mayores'].includes(category)?'u13':null;if(!template)throw Error('Categoría no admitida');if((template==='mini')!==/\b(PREMINI|MINI)\b/.test(norm(team.categoryName)))throw Error('La plantilla seleccionada no corresponde a la categoría CABB');
 const roster=await c.roster(team);if(roster.filter((p:any)=>samePlayerName(p.Nombre,cabbName)).length!==1)throw Error('Elegí un único jugador del plantel CABB');await c.category(team);
 let account:any=null;for(let page=1;page<=100;page++){const {data,error}=await db.auth.admin.listUsers({page,perPage:100});if(error)throw error;account=data.users.find(u=>u.email?.toLowerCase()===email);if(account || data.users.length<100)break;}
 let createdAccount=false;if(!account){if(typeof body.password!=='string' || body.password.length<8)throw Error('La cuenta nueva necesita una contraseña inicial de al menos 8 caracteres');const {data,error}=await db.auth.admin.createUser({email,password:body.password,email_confirm:true});if(error)throw error;account=data.user;createdAccount=true;}
 const config={season,category,template,club:team.club,cabbName,dorsal:body.dorsal ?? null,primaryTournament:needed(body.tournamentLabel),tournaments:[{...team,label:body.tournamentLabel}],createdAt:new Date().toISOString()};
 const {data:existingPlayers}=await db.from('players').select('id,name').eq('user_id',account.id);if(existingPlayers?.length===1){const {data:old}=await db.from('player_data').select('data').eq('player_id',existingPlayers[0].id).eq('module','player_season_v1:'+season).maybeSingle();if(old?.data){if(old.data.template!==template)throw Error('La plantilla de esta temporada ya está configurada. Revisá la categoría con el coach.');if(!samePlayerName(old.data.cabbName,cabbName))throw Error('Esta cuenta ya tiene otra identidad CABB configurada.');const others=(old.data.tournaments || []).filter((t:any)=>!(t.club===team.club && t.categoryName===team.categoryName && t.competition===team.competition && t.federation===team.federation));config.tournaments=[...others,...config.tournaments];config.club=old.data.club;config.primaryTournament=old.data.primaryTournament;}}
 const {data:playerId,error}=await db.rpc('onboard_nextlevel_player',{account_id:account.id,display_name:displayName,club_name:team.club,category_name:category,shirt_number:body.dorsal ?? null,season_value:season,configuration:config});if(error)throw Error('El perfil no se vinculó: '+error.message+(createdAccount?' La cuenta quedó creada; repetí el alta con el mismo correo.':''));
 return answer({playerId,template,url:'perfil.html?player='+playerId+'&season='+season,syncPending:true});
 }catch(e){return answer({error:e.message},400);}
});
