(async function(){
 'use strict';
 const $=id=>document.getElementById(id),node=(tag,text,parent)=>{const n=document.createElement(tag);if(text!=null)n.textContent=String(text);if(parent)parent.append(n);return n;};
 let client,session,player,profile={},moduleName='perfil_v1',modules=new Map(),busy=false;
 const status=text=>$('status').textContent=text;
 const wipe=()=>{$('private').hidden=true;$('name').textContent='';$('identity').textContent='';$('photo').hidden=true;$('photo').removeAttribute('src');document.querySelectorAll('#private input,#private textarea').forEach(x=>x.value='');document.querySelectorAll('#private select').forEach(x=>x.selectedIndex=0);for(const id of ['season-stats','games','practices','goals','tests','assessments','measures','conversation'])$(id).replaceChildren();player=null;profile={};modules.clear();};
 const errorText=e=>e?.status===401||e?.status===403?'Tu sesión no permite esta operación. Volvé a ingresar.':e?.message||'No se pudo completar la operación.';
 function access(){wipe();$('access').hidden=false;$('logout').hidden=true;document.documentElement.classList.remove('locked');status('Ingresá con tu cuenta para continuar.');}
 async function execute(button,fn){if(busy)return;busy=true;if(button)button.disabled=true;try{await fn();}catch(e){if(session){try{session.assert();}catch(_){return;}}status(errorText(e));}finally{busy=false;if(button)button.disabled=false;}}
 const labels={date:'Fecha',fecha:'Fecha',rival:'Rival',torneo:'Torneo',tournament:'Torneo',season:'Temporada',pts:'Puntos',reb_tot:'Rebotes',ast:'Asistencias',minutos:'Minutos',val:'Valoración',stl:'Recuperos',blk:'Tapones',to_perdidas:'Pérdidas',faltas:'Faltas',source:'Origen',success:'Lo que pude hacer',next:'Próximo paso',areas:'Áreas',body:'Mensaje',notes:'Notas',height:'Altura (cm)',weight:'Peso (kg)',wingspan:'Envergadura (cm)',test_type:'Prueba',value:'Resultado',unit:'Unidad',height_cm:'Altura (cm)',weight_kg:'Peso (kg)',wingspan_cm:'Envergadura (cm)',ppg:'Puntos por partido',rpg:'Rebotes por partido',apg:'Asistencias por partido',pj:'Partidos',seasonGoal:'Objetivo',dream:'Mi sueño',goal:'Objetivo',done:'Completado',text:'Texto',name:'Nombre',title:'Título',enjoy:'Qué disfruto',learn:'Qué quiero aprender',position:'Posición',mentalAreas:'Áreas mentales',technicalAreas:'Áreas técnicas'};
 const skip=new Set(['id','player_id','user_id','coach_id','module','foto','foto_url','data_url','photo','synced_at','createdAt','created_at','updated_at','cabb_player_id','cabb_partido_id']);
 function showValue(parent,value,depth=0){if(depth>5){node('p','Contenido extenso disponible en tu cuenta.',parent);return;}if(Array.isArray(value)){for(const v of value)showValue(parent,v,depth+1);if(!value.length)node('p','Sin registros.',parent);return;}if(value&&typeof value==='object'){const dl=node('dl',null,parent);for(const [key,v] of Object.entries(value)){if(skip.has(key)||v==null||v==='')continue;node('dt',labels[key]||key.replace(/[_-]/g,' '),dl);const dd=node('dd',null,dl);showValue(dd,v,depth+1);}return;}if(typeof value==='string'&&/^data:image\//.test(value))return;node('span',typeof value==='boolean'?(value?'Sí':'No'):value,parent);}
 function records(host,title,rows){const h=$(host);node('h3',title,h);if(!rows.length){node('p','Todavía no hay registros guardados.',h);return;}for(const value of rows)showValue(node('article',null,h),value);}
 function photo(value){$('photo').hidden=true;$('photo').removeAttribute('src');if(typeof value==='string'&&/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(value)&&value.length<1000000){$('photo').src=value;$('photo').hidden=false;}}
 const miniToMature={birthDate:'fnac',dominantHand:'mano',contactEmail:'email',whatsapp:'wsp',height:'altura',weight:'peso',wingspan:'enverg',coachNote:'nota'};
 function fillProfile(){profile={...(modules.get(moduleName)||{})};const model={...profile};if(moduleName==='mini_profile_v1'){for(const [from,to] of Object.entries(miniToMature))model[to]=profile[from]??'';model.mano=({Derecha:'D',Izquierda:'I','Uso ambas manos':'A'})[profile.dominantHand]||'';}
 const season=String(new Date().getFullYear());model.dream=profile.dream||profile.obj||'';model.seasonGoal=profile.seasonGoals?.[season]??((profile.seasonGoalSeason||'2026')===season?profile.seasonGoal||'':'');
 document.querySelectorAll('[data-field]').forEach(el=>el.value=model[el.dataset.field]??'');}
 async function openProfile(){
  $('access').hidden=true;status('Cargando tu perfil…');session=await NextLevelSecurity.guard(client,window,wipe);
  try{player=await NextLevelData.ownPlayer(client,session,new URLSearchParams(location.search).get('player'));session.assert();
   const results=await Promise.allSettled(NextLevelData.readTables.map(t=>NextLevelData.rows(client,session,t,player.id)));session.assert();
   const data={};const failures=[];results.forEach((r,i)=>{const t=NextLevelData.readTables[i];if(r.status==='fulfilled')data[t]=r.value;else{data[t]=[];failures.push(t);}});
   if(failures.includes('player_data'))throw Error('No se pudo cargar tu perfil. Recargá para evitar guardar sobre datos incompletos.');
   modules=new Map(data.player_data.map(r=>[r.module,r.data]));moduleName=/\b(U11|U9|MINI|PREMINI)\b/i.test(player.category||'')?'mini_profile_v1':'perfil_v1';
   if(!modules.has(moduleName)&&modules.has(moduleName==='perfil_v1'?'mini_profile_v1':'perfil_v1'))moduleName=moduleName==='perfil_v1'?'mini_profile_v1':'perfil_v1';
   $('name').textContent=player.name||'Mi perfil';$('identity').textContent=[player.club,player.category,player.dorsal!=null?'Dorsal '+player.dorsal:''].filter(Boolean).join(' · ');fillProfile();photo(modules.get('foto_url'));
   records('season-stats','Resumen por temporada',data.stats_seasons);records('games','Historial de partidos',data.game_log.slice().sort((a,b)=>String(b.fecha).localeCompare(String(a.fecha))));
   records('practices','Mis prácticas guardadas',data.player_data.filter(r=>r.module.startsWith('plan_progress_v1:')).map(r=>r.data).sort((a,b)=>String(b.date).localeCompare(String(a.date))));
   records('goals','Objetivos y avances',data.player_data.filter(r=>r.module.startsWith('gradual_goals_v1:')).map(r=>r.data));records('goals','Tareas de mi plan',data.plan_progress);
   records('tests','Pruebas físicas',data.physical_test_results);records('assessments','Evaluaciones guardadas',data.evaluations);records('measures','Mis medidas registradas',data.player_data.filter(r=>r.module.startsWith('mini_measures_v1:')).map(r=>r.data));
   records('conversation','Mensajes',data.messages);records('conversation','Respuestas guardadas',data.message_replies);records('conversation','Devoluciones del coach',data.player_data.filter(r=>r.module==='coach_eval_v1'||r.module.startsWith('coach_conversation_v1:')).map(r=>r.data));
   $('practice-date').value=new Date().toLocaleDateString('en-CA');$('practice-date').max=$('practice-date').value;document.querySelector('[data-field=fnac]').max=$('practice-date').value;
   session.assert();$('private').hidden=false;$('logout').hidden=false;status(failures.length?'Tu perfil está cargado, pero algunas secciones no se pudieron consultar. Recargá para volver a intentarlo.':'Perfil cargado desde tu cuenta.');
   history.replaceState(null,'','perfil.html?player='+encodeURIComponent(player.id));
  }catch(e){wipe();$('logout').hidden=false;status(errorText(e));}
 }
 $('login-form').addEventListener('submit',e=>{e.preventDefault();execute(e.submitter,async()=>{status('Verificando…');const password=$('password').value;const email=$('email').value.trim();$('password').value='';const result=await client.auth.signInWithPassword({email,password});if(result.error)throw Error('No se pudo ingresar. Revisá tu correo y contraseña.');$('email').value='';await openProfile();});});
 $('logout').addEventListener('click',()=>execute($('logout'),async()=>{wipe();status('Cerrando sesión…');try{const {error}=await client.auth.signOut({scope:'local'});if(error)throw error;}finally{localStorage.removeItem('sb-yjcxwfkedxzkcspddghz-auth-token');session?.end();location.replace('login.html');}}));
 $('profile-form').addEventListener('submit',e=>{e.preventDefault();execute(e.submitter,async()=>{session.assert();if(!e.target.reportValidity())return;const fields={};document.querySelectorAll('[data-field]').forEach(el=>fields[el.dataset.field]=el.value.trim());const next={...profile};if(moduleName==='mini_profile_v1'){for(const [from,to] of Object.entries(miniToMature))next[from]=fields[to];next.dominantHand=({D:'Derecha',I:'Izquierda',A:'Uso ambas manos'})[fields.mano]||'';}else Object.assign(next,fields);const season=String(new Date().getFullYear());next.position=fields.position;next.dream=fields.dream;next.seasonGoal=fields.seasonGoal;next.seasonGoalSeason=season;next.seasonGoals={...(profile.seasonGoal?{[profile.seasonGoalSeason||'2026']:profile.seasonGoal}:{}),...profile.seasonGoals,[season]:fields.seasonGoal};await NextLevelData.saveModule(client,session,player.id,moduleName,next);profile=next;modules.set(moduleName,next);status('Perfil guardado en Supabase.');});});
 $('practice-form').addEventListener('submit',e=>{e.preventDefault();execute(e.submitter,async()=>{session.assert();const date=$('practice-date').value;const success=$('practice-success').value.trim(),area=$('practice-area').value.trim();if(!date||date>$('practice-date').max||!success||!area)throw Error('Revisá la fecha y completá tu práctica.');const entry={id:crypto.randomUUID(),date,areas:[area],success,next:$('practice-next').value.trim(),source:'player_training',createdAt:new Date().toISOString()};await NextLevelData.saveModule(client,session,player.id,'plan_progress_v1:'+entry.id,entry);showValue(node('article',null,$('practices')),entry);$('practice-success').value=$('practice-next').value='';status('Práctica guardada en Supabase.');});});
 $('photo-input').addEventListener('change',e=>execute($('photo-input'),async()=>{const file=e.target.files?.[0];if(!file)return;try{session.assert();if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)throw Error('Elegí una foto JPG, PNG o WebP de hasta 5 MB.');const image=await createImageBitmap(file);const scale=Math.min(1,640/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);image.close();const value=canvas.toDataURL('image/jpeg',.82);if(value.length>750000)throw Error('Elegí una foto más pequeña.');session.assert();await NextLevelData.saveModule(client,session,player.id,'foto_url',value);photo(value);status('Foto guardada en tu perfil privado.');}finally{e.target.value='';}}));
 document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>{session.assert();document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==button.dataset.tab);document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));}));
 async function start(){try{client=supabase.createClient(NextLevelAppConfig.url,NextLevelAppConfig.anonKey);const result=await client.auth.getUser();if(!result.error&&result.data?.user)await openProfile();else access();}catch(e){access();status(errorText(e));}}
 $('clear-legacy').addEventListener('click',()=>{NextLevelSecurity.eraseLegacy(localStorage);NextLevelSecurity.eraseLegacy(sessionStorage);$('legacy').hidden=true;start();});
 try{if(NextLevelSecurity.legacyKeys(localStorage).length||NextLevelSecurity.legacyKeys(sessionStorage).length){$('legacy').hidden=false;status('Hay copias de la versión anterior que requieren tu decisión.');}else await start();}catch(e){status('El navegador no permite comprobar el almacenamiento. Usá una ventana nueva para continuar.');}
})();
