const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{stripTypeScriptTypes}=require('node:module');
const source=fs.readFileSync(__dirname+'/../supabase/functions/nextlevel-onboard/index.ts','utf8');let handler,actor='275323dc-c40c-4e3d-b6db-00147bf30b4d',role='admin_coach',authError=false,roleError=false,calledRole=0;
const db={auth:{getUser:async()=>({data:{user:{id:actor}},error:authError?Error('Denied'):null})}};
const context={Deno:{env:{get:key=>key==='SUPABASE_SERVICE_ROLE_KEY'?'TEST_SERVICE':key==='SUPABASE_ANON_KEY'?'TEST_ANON':'https://example.invalid'},serve:fn=>handler=fn},createClient:(url,key,options)=>options?{rpc:async()=>{calledRole++;return {data:role,error:roleError?Error('Revoked'):null};}}:db,Response,Set,Map,Request,URLSearchParams,AbortSignal,crypto,console};
vm.createContext(context);vm.runInContext(stripTypeScriptTypes(source).replace(/^import .*$/m,''),context);
let checks=0;const check=(a,b)=>{assert.deepEqual(a,b);checks++;};
const request=token=>new Request('https://example.invalid/functions/v1/nextlevel-onboard',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({action:'capabilities'})});
(async()=>{let r=await handler(request('COACH_JWT'));check(r.status,200);const result=await r.json();check(result.accounts,true);check(result.sync,true);check(JSON.stringify(result).includes('TEST_SERVICE'),false);actor='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';const before=calledRole;r=await handler(request('PLAYER_JWT'));check(r.status,403);check(calledRole,before);actor='275323dc-c40c-4e3d-b6db-00147bf30b4d';role='player';check((await handler(request('COACH_JWT'))).status,403);role='admin_coach';roleError=true;check((await handler(request('COACH_JWT'))).status,403);roleError=false;authError=true;check((await handler(request('INVALID_JWT'))).status,403);authError=false;check((await handler(request('TEST_SERVICE'))).status,403);check((await handler(new Request('https://example.invalid',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}))).status,403);
const start=source.indexOf('async function syncPlayer('),end=source.indexOf('async function verifyChangedPassword');const sync=source.slice(start,end);check(sync.includes("await stageWrite('game_log'"),true);check(sync.indexOf('for(const write of writes)')>sync.indexOf("'sync_status_v1:'"),true);check(source.includes("player.user_id===COACH_ID"),true);check(source.includes('account?.id===COACH_ID'),true);console.log(checks+' comprobaciones del backend preparado aprobadas. Sin cambios reales.');})().catch(e=>{console.error(e);process.exitCode=1;});
