const {PGlite}=require('@electric-sql/pglite'),{readFileSync}=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path');
(async()=>{
const db=new PGlite();const a='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',b='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',coach='275323dc-c40c-4e3d-b6db-00147bf30b4d',pa='11111111-1111-4111-8111-111111111111',pb='22222222-2222-4222-8222-222222222222';
await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;create table auth.users(id uuid primary key,email_confirmed_at timestamptz,deleted_at timestamptz,banned_until timestamptz);insert into auth.users values('${coach}',now(),null,null),('${a}',now(),null,null),('${b}',now(),null,null);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema public,auth,storage to anon,authenticated;create table players(id uuid primary key,user_id uuid);insert into players values('${pa}','${a}'),('${pb}','${b}');create table player_data(player_id uuid,module text,data jsonb,unique(player_id,module));create table evaluations(id uuid default gen_random_uuid(),player_id uuid);create table game_log(id uuid,player_id uuid);create table stats_seasons(id uuid,player_id uuid);create table hidden_future_data(secret text);create table storage.buckets(id text primary key,public boolean);create table storage.objects(bucket_id text,name text);alter table storage.objects enable row level security;`);
await db.exec(readFileSync(path.join(__dirname,'../supabase/migrations/20261009000000_owner_only.sql'),'utf8'));const sql=readFileSync(path.join(__dirname,'../supabase/migrations/20261010000000_admin_coach.sql'),'utf8');await db.exec(sql);await db.exec(sql);let count=0;
async function role(id){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');}
async function denied(sql){await assert.rejects(()=>db.exec(sql));count++;}async function rows(sql,n){assert.equal((await db.query(sql)).rows.length,n);count++;}
await role(a);await rows('select * from players',1);assert.equal((await db.query('select public.nextlevel_access_role() as r')).rows[0].r,'player');count++;await denied('select * from nextlevel_private.staff_accounts');await denied(`insert into nextlevel_private.staff_accounts values('${a}','admin_coach',true,now())`);await denied(`insert into player_data values('${pa}','coach_eval_v1','{"author_id":"${a}"}')`);await denied(`insert into evaluations(player_id) values('${pb}')`);
await role(coach);await rows('select * from players',2);assert.equal((await db.query('select public.nextlevel_access_role() as r')).rows[0].r,'admin_coach');count++;await db.exec(`insert into player_data values('${pa}','coach_eval_v1','{"author_id":"${coach}","author_type":"coach"}'),('${pb}','perfil_v1','{}')`);count++;await db.exec(`insert into evaluations(player_id) values('${pb}')`);count++;await denied(`insert into player_data values('${pb}','coach_eval_v1','{"author_id":"${a}"}')`);await denied(`insert into player_data values('${pb}','player_season_v1:2026','{}')`);await denied(`insert into stats_seasons(player_id) values('${pb}')`);await denied(`update players set user_id='${coach}'`);await denied('select * from hidden_future_data');
await db.exec('reset role');await db.exec(`update nextlevel_private.staff_accounts set active=false where user_id='${coach}'`);await role(coach);await rows('select * from players',0);await denied(`insert into evaluations(player_id) values('${pa}')`);await role(b);await rows('select * from players',1);await rows(`select * from player_data where player_id='${pa}'`,0);await db.exec('reset role;set role anon');await denied('select * from players');await denied('select public.nextlevel_access_role()');await denied('select * from nextlevel_private.staff_accounts');console.log(count+' pruebas de coach, jugadores, autoría, estadísticas, revocación y anonimato aprobadas.');await db.close();

})().catch(e=>{console.error(e);process.exit(1);});
