const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');
const dir=path.join(__dirname,'../private-app');
const a='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',b='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',pa='11111111-1111-4111-8111-111111111111',pb='22222222-2222-4222-8222-222222222222';
let passed=0;const check=(actual,expected)=>{assert.deepEqual(actual,expected);passed++;};
async function fixture({identity=a,requested=pa,legacy=false,delay=false,failWrites=false}={}){
 const dom=new JSDOM(fs.readFileSync(path.join(dir,'index.html'),'utf8'),{url:'https://example.com/NextLevel/revision/perfil.html'+(requested?'?player='+requested:''),runScripts:'outside-only'}),w=dom.window;
 let account=identity,callback,release;const calls=[],saved=[];
 const dataset={game_log:[{id:'g1',player_id:pa,torneo:'Torneo A',fecha:'2026-01-01',pts:0,reb_tot:2,ast:1,minutos:10,t2_in:1,t2_att:2},{id:'g2',player_id:pa,torneo:'Torneo A',fecha:'2026-01-02',pts:10,reb_tot:4,ast:3,minutos:20,t2_in:3,t2_att:4},{id:'g3',player_id:pa,torneo:'Torneo B',fecha:'2026-02-01',pts:null}],players:[{id:pa,user_id:a,name:'Cuenta A',category:'U13',club:'Club'},{id:pb,user_id:b,name:'Cuenta B',category:'U11'}],player_data:[{player_id:pa,module:'perfil_v1',data:{dream:'Sueño A',obj:'Antiguo',untouched:'Conservar',seasonGoals:{2025:'Antes'}}},{player_id:pb,module:'mini_profile_v1',data:{dream:'Sueño B'}},{player_id:pa,module:'coach_eval_v1',data:{body:'<img src=x onerror=alert(1)>'}}]};
 const client={auth:{getUser:async()=>({data:{user:account?{id:account}:null},error:null}),onAuthStateChange:fn=>{callback=fn;return{data:{subscription:{unsubscribe(){}}}};},signInWithPassword:async()=>({data:{user:{id:account}},error:null}),signOut:async()=>{account=null;callback?.('SIGNED_OUT',null);return{error:null};}},from:table=>{
  const filters=[],q={select(){return q;},eq(k,v){filters.push([k,v]);return q;},order(){return q;},range(){return q;},limit(){return q;},upsert(payload){saved.push(payload);return Promise.resolve({error:failWrites?Error('Sin conexión'):null});},insert(payload){saved.push(payload);return Promise.resolve({error:failWrites?Error('Sin conexión'):null});},async then(resolve){calls.push({table,filters});if(delay&&table==='player_data')await new Promise(r=>release=r);const data=(dataset[table]||[]).filter(row=>filters.every(([k,v])=>row[k]===v));resolve({data,error:null});}};return q;
 }};
 w.NextLevelAppConfig={url:'https://example.supabase.co',anonKey:'public'};w.supabase={createClient:()=>client};w.crypto.randomUUID=()=>pa;
 if(legacy)w.localStorage.setItem('nl_pf_legacy','UNSCOPED');
 for(const name of ['security.js','data.js','app.js'])w.eval(fs.readFileSync(path.join(dir,name),'utf8'));
 const settle=()=>new Promise(r=>setTimeout(r,40));await settle();
 return{w,dom,calls,saved,settle,setAccount:id=>account=id,switch:()=>callback('SIGNED_IN',{user:{id:b}}),logout:()=>callback('SIGNED_OUT',null),release:()=>release?.()};
}
(async()=>{
 let f=await fixture({identity:null});check(f.w.document.getElementById('access').hidden,false);check(f.calls.length,0);check(f.w.document.getElementById('private').hidden,true);f.dom.window.close();
 f=await fixture({requested:pb});check(f.w.document.getElementById('private').hidden,true);check(f.calls.filter(x=>x.table==='player_data').length,0);check(f.calls[0].filters,[['user_id',a],['id',pb]]);f.dom.window.close();
 f=await fixture();assert.equal(f.w.document.getElementById('name').textContent,'Cuenta A',f.w.document.getElementById('status').textContent);passed++;check(f.w.document.getElementById('private').hidden,false);check(f.calls.every(c=>c.table==='players'||c.filters.some(([k,v])=>k==='player_id'&&v===pa)),true);check(f.w.document.querySelector('#conversation img'),null);check(f.w.document.getElementById('conversation').textContent.includes('<img'),true);
 check(f.w.document.querySelector('#performance strong').textContent,'5.0');check(f.w.document.getElementById('performance').textContent.includes('66.7% · 4/6'),true);check(f.w.document.querySelectorAll('#performance tbody tr').length,2);const tournament=f.w.document.querySelector('#performance select');tournament.value='Torneo B';tournament.dispatchEvent(new f.w.Event('change'));check(f.w.document.querySelector('#performance strong').textContent,'Sin datos completos');check(f.w.document.querySelector('#performance tbody').textContent.includes('Sin datos'),true);check(f.w.document.querySelectorAll('#performance svg rect').length,0);
 const dream=f.w.document.querySelector('[data-field=dream]');dream.value='Actualizado';f.w.document.getElementById('profile-form').requestSubmit();await f.settle();check(f.saved[0].player_id,pa);check(f.saved[0].data.dream,'Actualizado');check(f.saved[0].data.untouched,'Conservar');check(f.saved[0].data.seasonGoals[2025],'Antes');check(f.w.localStorage.length,0);check(f.w.sessionStorage.length,0);
 const practice=f.w.document.getElementById('practice-form');f.w.document.getElementById('practice-area').value='Tiro';f.w.document.getElementById('practice-success').value='Prueba';f.w.document.getElementById('shot-made').value='3';f.w.document.getElementById('shot-attempts').value='2';practice.requestSubmit();await f.settle();check(f.saved.length,1);f.w.document.getElementById('shot-attempts').value='5';practice.requestSubmit();await f.settle();check(f.saved.length,2);check(f.saved[1].data.shots.made,3);check(f.saved[1].data.shots.attempts,5);check(f.w.document.getElementById('practice-summary').textContent.includes('60.0%'),true);
 const metric=f.w.document.querySelector('[aria-label="Tipo de objetivo"]');metric.value='practice_handling';f.w.document.querySelector('#goal-controls form').requestSubmit();await f.settle();check(f.saved.length,3);check(f.saved[2].data.metric,'practice_handling');check(f.saved[2].module.startsWith('gradual_goals_v1:'),true);check(f.w.document.getElementById('goal-cards').textContent.includes('Activo'),true);f.w.document.querySelector('[data-measure=height_cm]').value='150';f.w.document.getElementById('evaluation-form').requestSubmit();await f.settle();check(f.saved.length,4);check(f.saved[3].height_cm,150);check(f.saved[3].player_id,pa);check(f.w.document.getElementById('evaluation-history').textContent.includes('150'),true);
 f.switch();check(f.w.document.getElementById('private').hidden,true);check(f.w.document.getElementById('name').textContent,'');check(dream.value,'');check(f.w.document.getElementById('performance').textContent,'');check(f.w.document.getElementById('practice-summary').textContent,'');check(f.w.document.getElementById('goal-cards').textContent,'');check(f.w.document.getElementById('evaluation-history').textContent,'');check(f.w.document.getElementById('conversation').textContent,'');check(f.w.document.documentElement.classList.contains('locked'),true);f.dom.window.close();
 f=await fixture({identity:b,requested:pb});check(f.w.document.getElementById('name').textContent,'Cuenta B');check(f.w.document.querySelector('[data-field=dream]').value,'Sueño B');f.logout();check(f.w.document.getElementById('private').hidden,true);f.dom.window.close();
 f=await fixture({failWrites:true});f.w.document.getElementById('practice-area').value='Tiro';f.w.document.getElementById('practice-success').value='Prueba';f.w.document.getElementById('practice-form').requestSubmit();await f.settle();check(f.w.document.querySelectorAll('#practices article').length,0);check(f.w.document.getElementById('status').textContent,'Sin conexión');f.w.document.querySelector('[data-measure=height_cm]').value='150';f.w.document.getElementById('evaluation-form').requestSubmit();await f.settle();check(f.w.document.getElementById('evaluation-history').textContent.includes('150'),false);f.w.document.querySelector('[aria-label="Tipo de objetivo"]').value='practice_handling';f.w.document.querySelector('#goal-controls form').requestSubmit();await f.settle();check(f.w.document.getElementById('goal-cards').textContent.includes('Activo'),false);f.dom.window.close();
 f=await fixture({legacy:true});check(f.calls.length,0);check(f.w.document.getElementById('legacy').hidden,false);check(f.w.document.body.textContent.includes('UNSCOPED'),false);check(f.w.localStorage.getItem('nl_pf_legacy'),'UNSCOPED');f.w.localStorage.setItem('nextlevel_theme_v1','light');f.w.localStorage.setItem('sb-project-auth-token','token');f.w.document.getElementById('clear-legacy').click();await f.settle();check(f.w.localStorage.getItem('nl_pf_legacy'),null);check(f.w.localStorage.getItem('nextlevel_theme_v1'),'light');check(f.w.localStorage.getItem('sb-project-auth-token'),'token');f.dom.window.close();
 f=await fixture({delay:true});f.logout();f.release();await f.settle();check(f.w.document.getElementById('private').hidden,true);check(f.w.document.getElementById('name').textContent,'');f.dom.window.close();
 const sec=require('../private-app/security.js');let callback,identity=a,ended=0,redirects=0,hidden=false,show,visibility;
 const surface={document:{visibilityState:'visible',documentElement:{classList:{add(){hidden=true;},remove(){hidden=false;}}},addEventListener:(n,fn)=>visibility=fn,removeEventListener(){}},location:{replace(){redirects++;}},addEventListener:(n,fn)=>{if(n==='pageshow')show=fn;},removeEventListener(){},setInterval(){return 1;},clearInterval(){}};
 const guard=await sec.guard({auth:{getUser:async()=>({data:{user:{id:identity}},error:null}),onAuthStateChange:fn=>{callback=fn;return{data:{subscription:{unsubscribe(){}}}};}}},surface,()=>ended++);
 identity=b;show({persisted:true});await new Promise(r=>setTimeout(r,1));check(hidden,true);check(ended,1);check(redirects,1);assert.throws(()=>guard.assert());passed++;guard.dispose();
 console.log(passed+' comprobaciones de acceso, cuenta ajena, guardado, datos antiguos, cierre y respuestas tardías: aprobadas.');
})().catch(e=>{console.error(e);process.exit(1);});
