const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');
const dir=path.join(__dirname,'../private-app');
const a='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',b='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',pa='11111111-1111-4111-8111-111111111111',pb='22222222-2222-4222-8222-222222222222';
const reactionButton=(w,emoji)=>[...w.document.querySelectorAll('button[aria-label]')].find(b=>b.getAttribute('aria-label')==='Reaccionar '+emoji)||null;
let passed=0;const check=(actual,expected)=>{assert.deepEqual(actual,expected);passed++;};
async function fixture({identity=a,requested=pa,legacy=false,delay=false,failWrites=false,coach=false,snapshots=false,messages=false,miniOfficial=false}={}){
 const dom=new JSDOM(fs.readFileSync(path.join(dir,'index.html'),'utf8'),{url:'https://example.com/NextLevel/revision/perfil.html'+(requested?'?player='+requested:''),runScripts:'outside-only'}),w=dom.window;
 let account=identity,callback,release;const calls=[],saved=[];
 const dataset={game_log:[{id:'g1',player_id:pa,torneo:'Torneo A',fecha:'2026-01-01',pts:0,reb_tot:2,ast:1,minutos:10,t2_in:1,t2_att:2},{id:'g2',player_id:pa,torneo:'Torneo A',fecha:'2026-01-02',pts:10,reb_tot:4,ast:3,minutos:20,t2_in:3,t2_att:4},{id:'g3',player_id:pa,torneo:'Torneo B',fecha:'2026-02-01',pts:null}],players:[{id:pa,user_id:a,name:'Cuenta A',category:'U13',club:'Club'},{id:pb,user_id:b,name:'Cuenta B',category:'U11'}],player_data:[{player_id:pa,module:'perfil_v1',data:{dream:'Sueño A',obj:'Antiguo',untouched:'Conservar',seasonGoals:{2025:'Antes'}}},{player_id:pb,module:'mini_profile_v1',data:{dream:'Sueño B'}},{player_id:pa,module:'coach_eval_v1',data:{body:'<img src=x onerror=alert(1)>'}}]};

 if(snapshots){const year=new Date().getFullYear();dataset.player_data.push({player_id:pa,module:'cabb_shots_v1:'+year,data:{games:[{matched:true,tournament:'A',shots:[{zona:'Z1-IZ',accion_tipo:'CANASTA-2P'},{zona:'Z1-DE',accion_tipo:'TIRO2-FALLADO'}]},{matched:false,tournament:'A',shots:[{zona:'Z2',accion_tipo:'CANASTA-2P'}]}]}},{player_id:pa,module:'cabb_team_v1:'+year,data:{games:[{available:true,tournament:'A',players:[{name:'Equipo Uno',pts:12,ast:1},{name:'Equipo Dos',pts:12,ast:2}]},{available:true,tournament:'A',players:[{name:'Equipo Uno',pts:8,ast:3},{name:'Equipo Dos',pts:8,ast:2}]}]}});}

 if(messages){dataset.messages=[{id:'cccccccc-cccc-4ccc-8ccc-cccccccccccc',player_id:pa,body:'Mensaje original <img src=x>',created_at:'2026-01-01',pinned:true},{id:'dddddddd-dddd-4ddd-8ddd-dddddddddddd',player_id:pb,body:'Privado B'}];dataset.message_replies=[{id:'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',player_id:pa,message_id:'cccccccc-cccc-4ccc-8ccc-cccccccccccc',body:'Respuesta anterior',created_at:'2026-01-02'}];dataset.player_data.push({player_id:pa,module:'coach_conversation_v1:old',data:{id:'old',body:'Conversación antigua',authorRole:'family',createdAt:'2026-01-03'}},{player_id:pa,module:'plan_progress_v1:'+pa,data:{id:pa,date:'2026-01-01',areas:['Defensa'],success:'Experiencia anterior'}});}
 if(miniOfficial){dataset.player_data.push({player_id:pb,module:'cabb_mini_official_v1:'+new Date().getFullYear(),data:{season:String(new Date().getFullYear()),club:'Club Mini',games:[{IdPartidoNotificacion:1,Fecha:'01/01/'+new Date().getFullYear(),NombreEquipoLocal:'Club Mini',NombreEquipoVisitante:'Otro Club',Resultados:{ResultadoLocal:20,ResultadoVisitante:18}}],boxscores:[{id:'1',player_rows:[{puntos:6,milisegundos_jugados:600000,valoracion:-1,faltascometidas:2,faltasrecibidas:3,canasta2p:2,tiro2p:4,canasta1p:2,tiro1p:3}]}]}});}
 const client={rpc:async()=>({data:coach?'admin_coach':'player',error:null}),auth:{getUser:async()=>({data:{user:account?{id:account}:null},error:null}),onAuthStateChange:fn=>{callback=fn;return{data:{subscription:{unsubscribe(){}}}};},signInWithPassword:async()=>({data:{user:{id:account}},error:null}),signOut:async()=>{account=null;callback?.('SIGNED_OUT',null);return{error:null};}},from:table=>{
  let deleting=false;const filters=[],q={delete(){deleting=true;return q;},select(){return q;},eq(k,v){filters.push([k,v]);return q;},order(){return q;},range(){return q;},limit(){return q;},upsert(payload){saved.push(payload);return Promise.resolve({error:failWrites?Error('Sin conexión'):null});},insert(payload){saved.push(payload);return Promise.resolve({error:failWrites?Error('Sin conexión'):null});},async then(resolve){calls.push({table,filters});if(deleting){saved.push({deleted:true,table,filters});resolve({error:failWrites?Error('Sin conexión'):null});return;}if(delay&&table==='player_data')await new Promise(r=>release=r);const data=(dataset[table]||[]).filter(row=>filters.every(([k,v])=>row[k]===v));resolve({data,error:null});}};return q;
 }};
 w.NextLevelAppConfig={url:'https://example.supabase.co',anonKey:'public'};w.supabase={createClient:()=>client};w.crypto.randomUUID=()=>pa;
 if(legacy)w.localStorage.setItem('nl_pf_legacy','UNSCOPED');
 for(const name of ['security.js','data.js','app.js'])w.eval(fs.readFileSync(path.join(dir,name),'utf8'));
 const settle=()=>new Promise(r=>setTimeout(r,40));await settle();
 return{w,dom,client,calls,saved,settle,setAccount:id=>account=id,switch:()=>callback('SIGNED_IN',{user:{id:b}}),logout:()=>callback('SIGNED_OUT',null),release:()=>release?.(),revokeCoach:()=>coach=false};
}
(async()=>{
 let f=await fixture({identity:null});check(f.w.document.getElementById('access').hidden,false);check(f.calls.length,0);check(f.w.document.getElementById('private').hidden,true);f.dom.window.close();
 f=await fixture({requested:pb});check(f.w.document.getElementById('private').hidden,true);check(f.calls.filter(x=>x.table==='player_data').length,0);check(f.calls[0].filters,[['user_id',a],['id',pb]]);f.dom.window.close();
 f=await fixture();assert.equal(f.w.document.getElementById('name').textContent,'Cuenta A',f.w.document.getElementById('status').textContent);passed++;check(f.w.document.getElementById('private').hidden,false);check(f.calls.every(c=>c.table==='players'||c.filters.some(([k,v])=>k==='player_id'&&v===pa)),true);check(f.w.document.querySelector('#conversation img'),null);check(f.w.document.getElementById('conversation').textContent.includes('<img'),true);
 check(f.w.document.querySelector('#performance strong').textContent,'5.0');check(f.w.document.getElementById('performance').textContent.includes('66.7% · 4/6'),true);check(f.w.document.querySelectorAll('#performance tbody tr').length,2);const tournament=f.w.document.querySelector('#performance select');tournament.value='Torneo B';tournament.dispatchEvent(new f.w.Event('change'));check(f.w.document.querySelector('#performance strong').textContent,'Sin datos completos');check(f.w.document.querySelector('#performance tbody').textContent.includes('Sin datos'),true);check(f.w.document.querySelectorAll('#performance svg rect').length,0);
 const dream=f.w.document.querySelector('[data-field=dream]');dream.value='Actualizado';f.w.document.getElementById('profile-form').requestSubmit();await f.settle();check(f.saved[0].player_id,pa);check(f.saved[0].data.dream,'Actualizado');check(f.saved[0].data.untouched,'Conservar');check(f.saved[0].data.seasonGoals[2025],'Antes');check(f.w.localStorage.length,0);check(f.w.sessionStorage.length,0);
 const practice=f.w.document.getElementById('practice-form');f.w.document.getElementById('practice-area').value='Tiro';f.w.document.getElementById('practice-success').value='Prueba';f.w.document.getElementById('shot-made').value='3';f.w.document.getElementById('shot-attempts').value='2';practice.requestSubmit();await f.settle();check(f.saved.length,1);f.w.document.getElementById('shot-attempts').value='5';practice.requestSubmit();await f.settle();check(f.saved.length,2);check(f.saved[1].data.shots.made,3);check(f.saved[1].data.shots.attempts,5);check(f.w.document.getElementById('practice-summary').textContent.includes('60.0%'),true);
 const metric=f.w.document.querySelector('[aria-label="Tipo de objetivo"]');metric.value='practice_handling';f.w.document.querySelector('#goal-controls form').requestSubmit();await f.settle();check(f.saved.length,3);check(f.saved[2].data.metric,'practice_handling');check(f.saved[2].module.startsWith('gradual_goals_v1:'),true);check(f.w.document.getElementById('goal-cards').textContent.includes('Activo'),true);f.w.document.querySelector('[data-measure=height_cm]').value='150';f.w.document.getElementById('evaluation-form').requestSubmit();await f.settle();check(f.saved.length,4);check(f.saved[3].height_cm,150);check(f.saved[3].player_id,pa);check(f.w.document.getElementById('evaluation-history').textContent.includes('150'),true);
 f.switch();check(f.w.document.getElementById('private').hidden,true);check(f.w.document.getElementById('name').textContent,'');check(dream.value,'');check(f.w.document.getElementById('performance').textContent,'');check(f.w.document.getElementById('practice-summary').textContent,'');check(f.w.document.getElementById('goal-cards').textContent,'');check(f.w.document.getElementById('evaluation-history').textContent,'');check(f.w.document.getElementById('conversation').textContent,'');check(f.w.document.documentElement.classList.contains('locked'),true);f.dom.window.close();
 f=await fixture({identity:b,requested:pb});check(f.w.document.getElementById('name').textContent,'Cuenta B');check(f.w.document.querySelector('[data-field=dream]').value,'Sueño B');f.logout();check(f.w.document.getElementById('private').hidden,true);f.dom.window.close();
 f=await fixture({coach:true,requested:pb});check(f.w.document.getElementById('name').textContent,'Cuenta B');check(f.w.document.getElementById('coach-directory').hidden,false);check(f.w.document.getElementById('coach-tools').hidden,false);check(f.w.document.querySelectorAll('#coach-directory option').length,3);f.w.document.querySelector('[data-coach-field=fortalezas]').value='Observación de prueba';f.w.document.getElementById('coach-form').requestSubmit();await f.settle();check(f.saved[0].player_id,pb);check(f.saved[0].module,'coach_eval_v1');check(f.saved[0].data.author_id,a);check(f.saved[0].data.author_type,'coach');f.w.document.getElementById('conversation-text').value='Mensaje de prueba';f.w.document.getElementById('conversation-form').requestSubmit();await f.settle();check(f.saved[1].data.author_type,'coach');f.revokeCoach();f.w.document.dispatchEvent(new f.w.Event('visibilitychange'));await f.settle();check(f.w.document.getElementById('private').hidden,true);check(f.w.document.getElementById('coach-directory').textContent,'');f.dom.window.close();
 f=await fixture({coach:true,requested:null});check(f.w.document.getElementById('private').hidden,true);check(f.w.document.getElementById('coach-directory').hidden,false);check(f.w.document.getElementById('status').textContent,'Elegí el jugador que querés consultar.');f.dom.window.close();
 f=await fixture({failWrites:true});f.w.document.getElementById('practice-area').value='Tiro';f.w.document.getElementById('practice-success').value='Prueba';f.w.document.getElementById('practice-form').requestSubmit();await f.settle();check(f.w.document.querySelectorAll('#practices article').length,0);check(f.w.document.getElementById('status').textContent,'Sin conexión');f.w.document.querySelector('[data-measure=height_cm]').value='150';f.w.document.getElementById('evaluation-form').requestSubmit();await f.settle();check(f.w.document.getElementById('evaluation-history').textContent.includes('150'),false);f.w.document.querySelector('[aria-label="Tipo de objetivo"]').value='practice_handling';f.w.document.querySelector('#goal-controls form').requestSubmit();await f.settle();check(f.w.document.getElementById('goal-cards').textContent.includes('Activo'),false);f.dom.window.close();
 f=await fixture({legacy:true});check(f.calls.length,0);check(f.w.document.getElementById('legacy').hidden,false);check(f.w.document.body.textContent.includes('UNSCOPED'),false);check(f.w.localStorage.getItem('nl_pf_legacy'),'UNSCOPED');f.w.localStorage.setItem('nextlevel_theme_v1','light');f.w.localStorage.setItem('sb-project-auth-token','token');f.w.document.getElementById('clear-legacy').click();await f.settle();check(f.w.localStorage.getItem('nl_pf_legacy'),null);check(f.w.localStorage.getItem('nextlevel_theme_v1'),'light');check(f.w.localStorage.getItem('sb-project-auth-token'),'token');f.dom.window.close();
 f=await fixture({delay:true});f.logout();f.release();await f.settle();check(f.w.document.getElementById('private').hidden,true);check(f.w.document.getElementById('name').textContent,'');f.dom.window.close();

 f=await fixture();let selector=f.w.document.querySelector('[aria-label="Métrica de evolución"]');check(selector.options.length,6);selector.value='ast';selector.dispatchEvent(new f.w.Event('change'));check(f.w.document.querySelector('#performance tbody').textContent.includes('3'),true);check(f.w.document.querySelector('#performance svg').getAttribute('aria-label').startsWith('Asistencias'),true);let length=f.w.document.querySelector('[aria-label="Cantidad de partidos"]');length.value='all';length.dispatchEvent(new f.w.Event('change'));check(f.w.document.getElementById('performance').textContent.includes('toda la temporada'),true);check(f.w.document.getElementById('performance').textContent.includes('Se necesitan 10 partidos'),true);f.dom.window.close();
 f=await fixture({coach:true});let reference=f.w.document.querySelector('[data-coach-field=participationReferenceMinutes]');reference.value='25.5';f.w.document.getElementById('coach-form').requestSubmit();await f.settle();check(f.saved[0].data.participationReferenceMinutes,25.5);reference.value='';f.w.document.querySelector('[data-coach-field=obs]').value='Nota';f.w.document.getElementById('coach-form').requestSubmit();await f.settle();check(f.saved[1].data.participationReferenceMinutes,null);f.dom.window.close();
 f=await fixture({identity:b,requested:pb});check(f.w.document.getElementById('mini-adventures').hidden,false);check(f.w.document.querySelectorAll('#mini-adventures button').length,5);f.w.document.querySelector('#mini-adventures button').click();await f.settle();check(f.saved[0].module,'mini_profile_v1');check(f.saved[0].data.adventureId,'radar');check(f.saved[0].data.dream,'Sueño B');check(f.w.document.getElementById('practice-area').value,'Mirar antes de pasar');f.logout();check(f.w.document.getElementById('mini-adventures').textContent,'');f.dom.window.close();
 f=await fixture();let bitmapClosed=0;f.w.createImageBitmap=async()=>({width:1000,height:700,close(){bitmapClosed++;}});f.w.HTMLCanvasElement.prototype.getContext=()=>({clearRect(){},drawImage(){}});f.w.HTMLCanvasElement.prototype.toDataURL=()=> 'data:image/jpeg;base64,YQ==';f.w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};f.w.HTMLDialogElement.prototype.close=function(){this.open=false;};const fileInput=f.w.document.getElementById('photo-input');Object.defineProperty(fileInput,'files',{value:[{type:'image/jpeg',size:100}]});fileInput.dispatchEvent(new f.w.Event('change'));await f.settle();check(f.w.document.querySelectorAll('dialog').length,1);[...f.w.document.querySelectorAll('dialog button')].find(b=>b.textContent==='Cancelar').click();await f.settle();check(f.saved.length,0);check(bitmapClosed,1);fileInput.dispatchEvent(new f.w.Event('change'));await f.settle();[...f.w.document.querySelectorAll('dialog button')].find(b=>b.textContent==='Usar foto').click();await f.settle();check(f.saved[0].module,'foto_url');check(f.saved[0].data,'data:image/jpeg;base64,YQ==');fileInput.dispatchEvent(new f.w.Event('change'));await f.settle();f.switch();await f.settle();check(f.w.document.querySelector('dialog'),null);check(f.saved.length,1);check(bitmapClosed,3);f.dom.window.close();

 f=await fixture({coach:true});let prints=0;f.w.print=()=>prints++;f.w.document.getElementById('export-profile').click();await f.settle();check(prints,1);check(f.w.document.getElementById('profile-report').textContent.includes('Cuenta A'),true);check(f.w.document.getElementById('profile-report').textContent.includes('Cuenta B'),false);check(f.w.document.querySelector('#profile-report button'),null);f.w.dispatchEvent(new f.w.Event('afterprint'));check(f.w.document.getElementById('profile-report').textContent,'');f.dom.window.close();
 f=await fixture();for(const [key,value] of Object.entries({height_cm:150,weight_kg:45,wingspan_cm:155,sitting_height_cm:80,lane_agility_attempt1:14,lane_agility_attempt2:13.5,sprint_20m_attempt1:4.2,sprint_20m_attempt2:4.1}))f.w.document.querySelector('[data-measure='+key+']').value=value;f.w.document.getElementById('beep-level').value=2;f.w.document.getElementById('beep-shuttle').value=3;f.w.document.getElementById('evaluation-form').requestSubmit();await f.settle();check(f.saved[0].lane_agility_best,13.5);check(f.saved[0].sprint_20m_best,4.1);check(f.saved[0].yoyo_distance_meters,200);check(f.saved[0].yoyo_result,2.3);check(f.saved[0].bmi,20);check(f.saved[0].wingspan_minus_height_cm,5);check(f.saved[0].sitting_height_ratio,53.3);check(f.w.document.getElementById('beep-level').value,'');f.w.document.getElementById('beep-level').value=1;f.w.document.getElementById('beep-shuttle').value=8;f.w.document.getElementById('evaluation-form').requestSubmit();await f.settle();check(f.saved.length,1);check(f.w.document.getElementById('status').textContent.includes('Revisá nivel'),true);f.dom.window.close();

 f=await fixture({snapshots:true});check(f.w.document.querySelectorAll('#official-extras svg path').length,13);check(f.w.document.getElementById('official-extras').textContent.includes('50.0%'),true);check(f.w.document.querySelector('#official-extras tbody').textContent.includes('zona pintada12'),true);check(f.w.document.getElementById('official-extras').textContent.includes('Equipo Uno'),true);check(f.w.document.getElementById('official-extras').textContent.includes('10.0'),true);f.logout();check(f.w.document.getElementById('official-extras').textContent,'');f.dom.window.close();

 f=await fixture({identity:b,requested:pb,miniOfficial:true});check(f.w.document.getElementById('mini-profile-experiences').hidden,false);check(f.w.document.querySelectorAll('#mini-play-experiences input').length,4);f.w.document.querySelector('[data-mini-field=enjoy]').value='Jugar con amigos';f.w.document.querySelector('[data-mini-field=learn]').value='Pasar';f.w.document.querySelector('[data-mini-field=reach]').value=160;f.w.document.querySelector('#mini-play-experiences input').checked=true;f.w.document.getElementById('profile-form').requestSubmit();await f.settle();check(f.saved[0].data.enjoy,'Jugar con amigos');check(f.saved[0].data.learn,'Pasar');check(f.saved[0].data.dream,'Sueño B');check(f.saved[0].data.playExperiences[0],'Llevar la pelota');f.w.document.querySelector('[data-mini-measure=height]').value=140;f.w.document.getElementById('mini-measure-form').requestSubmit();await f.settle();check(f.saved[1].module.startsWith('mini_measures_v1:'),true);check(f.saved[1].data.height,140);check(f.saved[1].player_id,pb);check(f.w.document.getElementById('mini-measure-history').textContent.includes('140'),true);check(f.w.document.querySelector('[aria-label="Métrica de evolución"]').options.length,5);check(f.w.document.querySelector('#performance strong').textContent,'6.0');check(f.w.document.getElementById('mini-team-fixture').textContent.includes('20–18'),true);check(f.w.document.getElementById('season-milestones').textContent.includes('Sin verificación'),true);check(f.w.document.getElementById('official-extras').textContent,'');f.logout();check(f.w.document.getElementById('mini-measure-history').textContent,'');check(f.w.document.getElementById('mini-team-fixture').textContent,'');f.dom.window.close();
 f=await fixture({messages:true});check(f.w.document.getElementById('conversation').textContent.includes('Respuesta anterior'),true);check(f.w.document.getElementById('conversation').textContent.includes('Conversación antigua'),true);check(f.w.document.querySelector('#conversation img'),null);check(Number(!!reactionButton(f.w,'🙏')),1);reactionButton(f.w,'👍').click();await f.settle();check(f.saved[0].message_id,'cccccccc-cccc-4ccc-8ccc-cccccccccccc');check(f.saved[0].player_id,pa);check(reactionButton(f.w,'👍').getAttribute('aria-pressed'),'true');reactionButton(f.w,'👍').click();await f.settle();check(f.saved[1].deleted,true);check(f.saved[1].filters[0][1],pa);check(reactionButton(f.w,'👍').getAttribute('aria-pressed'),'false');const replyForm=f.w.document.querySelector('#conversation form');replyForm.querySelector('textarea').value='Respuesta nueva';replyForm.requestSubmit();await f.settle();check(f.saved[2].body,'Respuesta nueva');check(f.saved[2].message_id,'cccccccc-cccc-4ccc-8ccc-cccccccccccc');f.w.document.getElementById('conversation-speaker').value='family';f.w.document.getElementById('conversation-author').value='Familia A';f.w.document.getElementById('conversation-context').value=pa;f.w.document.getElementById('conversation-text').value='Sobre esta experiencia';f.w.document.getElementById('conversation-form').requestSubmit();await f.settle();check(f.saved[3].data.author_type,'player');check(f.saved[3].data.speaker,'family');check(f.saved[3].data.practiceId,pa);check(f.saved[3].data.author_id,a);f.w.confirm=()=>false;[...f.w.document.querySelectorAll('#conversation button')].find(b=>b.textContent==='Borrar mi respuesta').click();await f.settle();check(f.saved.length,4);await assert.rejects(()=>f.w.NextLevelData.replyLegacy(f.client,{id:a,verify:async()=>{},assert(){}},pa,'dddddddd-dddd-4ddd-8ddd-dddddddddddd','Ajeno'));passed++;f.switch();check(f.w.document.getElementById('conversation').textContent,'');check(f.w.document.getElementById('conversation-author').value,'');f.dom.window.close();
 f=await fixture();f.w.document.getElementById('self-test-type').value='lane_agility';f.w.document.getElementById('self-test-type').dispatchEvent(new f.w.Event('change'));f.w.document.getElementById('self-attempt-1').value=14;f.w.document.getElementById('self-attempt-2').value=13;f.w.document.getElementById('self-test-form').requestSubmit();await f.settle();check(f.saved[0].source,'self');check(f.saved[0].value,13);check(f.saved[0].test_type,'lane_agility');check(f.saved[0].player_id,pa);check(f.w.document.getElementById('self-test-history').textContent.includes('13 s'),true);f.w.document.getElementById('self-test-type').value='beep_test';f.w.document.getElementById('self-test-type').dispatchEvent(new f.w.Event('change'));f.w.document.getElementById('self-attempt-1').value=4;f.w.document.getElementById('self-attempt-2').value=1;f.w.document.getElementById('self-test-form').requestSubmit();await f.settle();check(f.saved[1].value,480);check(f.saved[1].attempt_3,24);f.dom.window.close();
 f=await fixture({coach:true,messages:true});check(f.w.document.getElementById('self-test-entry').hidden,true);check(f.w.document.getElementById('conversation-identity').hidden,true);check(reactionButton(f.w,'👍'),null);[...f.w.document.querySelectorAll('#conversation button')].find(b=>b.textContent==='Responder como coach').click();f.w.document.getElementById('conversation-text').value='Devolución';f.w.document.getElementById('conversation-form').requestSubmit();await f.settle();check(f.saved[0].data.legacyMessageId,'cccccccc-cccc-4ccc-8ccc-cccccccccccc');check(f.saved[0].data.author_type,'coach');check(f.saved[0].data.speaker,'coach');f.dom.window.close();
 const sec=require('../private-app/security.js');let callback,identity=a,ended=0,redirects=0,hidden=false,show,visibility;
 const surface={document:{visibilityState:'visible',documentElement:{classList:{add(){hidden=true;},remove(){hidden=false;}}},addEventListener:(n,fn)=>visibility=fn,removeEventListener(){}},location:{replace(){redirects++;}},addEventListener:(n,fn)=>{if(n==='pageshow')show=fn;},removeEventListener(){},setInterval(){return 1;},clearInterval(){}};
 const guard=await sec.guard({auth:{getUser:async()=>({data:{user:{id:identity}},error:null}),onAuthStateChange:fn=>{callback=fn;return{data:{subscription:{unsubscribe(){}}}};}}},surface,()=>ended++);
 identity=b;show({persisted:true});await new Promise(r=>setTimeout(r,1));check(hidden,true);check(ended,1);check(redirects,1);assert.throws(()=>guard.assert());passed++;guard.dispose();
 console.log(passed+' comprobaciones de acceso, cuenta ajena, guardado, datos antiguos, cierre y respuestas tardías: aprobadas.');
})().catch(e=>{console.error(e);process.exit(1);});
